# Exploratory Data Analysis

# Screenshots (Hidden to Save Space)

![image-15](image-15.png)

![image-16](image-16.png)

![image-17](image-17.png)

![image-18](image-18.png)

## Denver Airbnb Analyis Notes - Exploratory Data Analysis

The Denver Airbnb listing snapshot is heavily concentrated in entire-home/apartment listings, which account for 4,233 of 4,939 listings (85.71%).

No individual neighborhood dominates Denver's Airbnb inventory. Inventory is geographically distributed across many neighborhoods, although there is still meaningful concentration among the leading neighborhoods.
- Top 5 neighborhoods → 26.67%
- Top 10 → 42.01%
- Top 13 → 49.32%
- Top 16 → 55.68%
    
Location Quotient Rank by Room Type:
- Overland's shared-room LQ of 41.01 is enormous: shared rooms are 43.18% of Overland's listings versus only 1.05% citywide. You also have 19 actual shared-room listings, so this isn't being driven by one or two observations.
- Berkeley's hotel-room LQ of 21.10 tells a different story. Hotel rooms are only 9.83% of Berkeley inventory, but they're just 0.47% of Denver inventory overall. Berkeley contains 17 of Denver's 23 hotel-room listings—73.91% of the city's total in this dataset.
- For private rooms, Gateway–Green Valley Ranch is particularly compelling because it combines concentration with substantial volume: 91 private rooms, 46.43% of neighborhood inventory, versus 12.78% citywide, giving LQ = 3.63.
- Entire homes behave differently. Auraria, Marston, Fort Logan, Country Club, Cory-Merrill, and University Park show LQ ≈ 1.17 because they're 100% entire-home listings in this dataset. But Denver itself is already 85.71% entire homes, so even a neighborhood at 100% cannot produce an extreme LQ:

Host Scale Across Denver Neighbourhoods:
- Neighborhoods were required to have at least 5 distinct hosts and 10 listings to reduce instability in host- and listing-share percentages caused by very small neighborhood samples. Large/professional operators are defined by having 10+ listings across the Denver market, rather than 10+ listings within an individual neighborhood.

Pricing Analysis:
- Denver nightly prices are strongly right-skewed, with a median of $176.45 versus a mean of $276.04, a small but meaningful high-price tail, and several exceptionally extreme observations.
- There are no low-price outliers under our room-type-specific IQR definition.
- Roughly 1 in 10 priced listings exceeds $500, but only 1.46% exceeds $1,000. Once we reach $2,000, we're down to only 9 listings, and above $5,000 there are only 4.
- Price anomaly: Marion — Cheesman Park: Entire condo, accommodates 2, 30-night minimum, $110,616.60/night, estimated occupancy 0.
- 235 total high-price outliers among Entire home/apartment and Private rooms
- There is a very clear price hierarchy by accommodation type. Hotel rooms have the highest median at $378, followed by Entire home/apartment at about $191, Private rooms at $106, and Shared rooms at only $35.
- For Entire home/apartment, the mean is about $107 above the median. That's substantial positive skew and consistent with the 213 high-price outliers we identified. Private rooms show the same pattern, although less dramatically: mean $152.98 versus median $106.
- For Entire home/apt, removing the IQR-defined high-price outliers reduces the mean from $297.35 to $217.78. That's a reduction of about 26.8%. Yet the median moves only from $190.59 to $180.62, about 5.2%.
- Private rooms tell essentially the same story: the mean falls by $40.67, or about 26.6%, while the median falls by only about 3.8%.
- Full dataset → describes the actual observed listing-price distribution.
- Median → primary measure of typical price.
- IQR price_status → allows us to identify/analyze unusual prices.
- Outlier-excluded mean → useful sensitivity/robustness measure.
- Neighborhood price comparisons are limited to neighborhoods with at least 20 listings containing a valid nightly price. This threshold retains 93.67% of priced listings while reducing the influence of neighborhood estimates based on small samples.
- Hampden deserves slightly more caution. It passes our threshold, but only with 24 priced listings, and its interquartile range is enormous: IQR = 572.64 - 99.77 = $472.87. So "$356.50 is Hampden's median" is supported by the data, but I wouldn't make a strong claim that Hampden is definitively Denver's most expensive Airbnb neighborhood without acknowledging its relatively small and highly dispersed sample. Cherry Creek, Jefferson Park, Highland, and Berkeley have progressively stronger sample support.
- Neighborhood-level Entire home/apt price comparisons require at least 15 priced Entire home/apt listings. This retains 55 neighborhoods and 95.1% of Denver's priced Entire home/apt inventory while excluding neighborhoods with very small comparison samples.
- City Park, Capitol Hill, and Overland remain among the least expensive neighborhoods even after restricting the analysis to Entire homes/apartments.
- On the expensive side, Cherry Creek and Jefferson Park remain expensive after controlling for room type, while Hampden drops relative to them. This gives us evidence that neighborhood itself—or characteristics associated with those neighborhoods—is related to price beyond just room-type composition.
- Among priced Entire home/apt listings with 1–3 bedrooms, single-listing hosts have higher median nightly prices than the Denver-wide median for each corresponding bedroom count, while small and medium multi-listing operators consistently fall below those benchmarks. Large/professional operators show a mixed pattern, with below-benchmark 1–2 bedroom prices but above-benchmark 3-bedroom prices.
- Among the 41 comparable neighborhood × bedroom segments with at least three listings from each host type, Single-listing hosts have a higher median nightly price in 28 segments (68.3%), while large/professional operators have a higher median in 13 segments (31.7%).
- After controlling for neighborhood and bedroom count among comparable 1–3 bedroom Entire home/apt segments, Single-listing hosts had higher median nightly prices in 68.3% of comparisons. Across all 41 comparisons, the median signed difference was +28.5% relative to large/professional operators, while the typical absolute pricing gap was 35.6%.

Minimum night strategy analysis 
- Longer minimum-stay policies are associated with substantially lower nightly prices. The relationship persists after controlling for room type, particularly among entire-home/apartment listings, where monthly-stay listings have a median nightly price approximately 60% below short-stay listings.
- Among comparable 1–3 bedroom entire homes/apartments, monthly-stay listings have median nightly prices approximately 54–59% lower than short-stay listings. The discount persists across all three bedroom counts, suggesting that the relationship between longer minimum-stay requirements and lower nightly rates is not simply explained by differences in property size.
- Monthly-stay Entire home/apt listings have median nightly rates approximately 54–59% lower than comparable short-stay listings across 1-, 2-, and 3-bedroom properties.

Amenity analysis
- Amenity richness remains positively associated with nightly price even after controlling for room type and bedroom count, particularly among 2- and 3-bedroom entire-home listings. The relationship is weaker among 1-bedroom listings.
- Hot tubs are associated with a substantial nightly price premium among Denver entire-home Airbnb listings. After controlling for bedroom count, listings with hot tubs have median nightly prices approximately 16% higher for one-bedroom properties and 49% higher for both two- and three-bedroom properties.
- Amenity quantity: Listings with richer amenity sets tend to have higher nightly prices, particularly among larger properties.
- Amenity composition: Hot tubs specifically are associated with higher median prices: +16% for 1-bedroom and approximately +49% for 2- and 3-bedroom entire-home listings.
- Pools do not show the same pattern

Estimated occupancy analysis 
- Entire homes/apartments have substantially higher estimated occupancy than the other room types, and within entire homes/apartments, smaller 1-bedroom properties have higher estimated occupancy than 2- and 3-bedroom properties.
- Among comparable 1–3 bedroom entire-home listings, monthly-stay properties have substantially lower modeled occupancy than short-stay properties. Approximately 41–54% of monthly-stay listings have zero estimated occupied nights, compared with only 3–6% of short-stay listings.
- Estimated occupancy varies substantially across Denver neighborhoods even after restricting comparisons to similar listing types and bedroom counts, suggesting geography is associated with performance beyond differences in broad property composition.
- Listing structure matters: entire homes/apartments have substantially higher estimated occupancy than the other broad room types. Stay strategy matters: short-stay listings dramatically outperform monthly-stay listings in estimated occupancy, and monthly listings have extraordinarily high zero-estimated-occupancy rates. Location matters: substantial neighborhood differences remain even when controlling for room type, stay strategy, and bedroom count.
- After controlling for broad listing type, stay policy, and bedroom count, the relationship between nightly price and estimated occupancy does not appear strongly linear from the grouped medians alone.
- Among comparable 1–3 bedroom short-stay entire homes/apartments, Superhost listings consistently show substantially higher estimated occupancy than non-Superhost listings. Median estimated occupancy is roughly 92–119 nights higher for Superhosts depending on bedroom count, while zero-estimated-occupancy rates are substantially lower.
- Roughly 81% of the original 5.0 listings disappear when we require 20 reviews.
- Guest rating alone showed a misleading relationship with estimated occupancy. Perfect 5.0 listings initially had much lower estimated occupancy than listings rated 4.5–4.99, but perfect-rated listings also had substantially fewer reviews. After restricting the comparison to listings with at least 20 reviews, the median estimated occupancy gap narrowed from 80 nights to 14 nights (168 vs. 154), suggesting listing maturity/review volume explains much of the original difference.
- Single-listing and medium-scale hosts show substantially higher estimated occupancy per listing than large/professional operators, while small multi-listing hosts fall between those extremes.
- Among comparable 1–3 bedroom short-stay entire homes/apartments, single-listing hosts had substantially higher estimated occupancy than large/professional operators, with median estimated occupancy of 161 versus 84 nights. Large/professional operators had a somewhat higher incidence of zero estimated occupancy (6.8% vs. 3.87%), but this difference is too small to account for the overall occupancy gap, suggesting lower estimated occupancy is more broadly distributed across their listings. Medium operators were an exception, showing occupancy comparable to single-listing hosts, although the group contained only 81 listings.

Estimated revenue analysis
- Among comparable short-stay entire homes/apartments, larger listings commanded substantially higher nightly prices but had lower estimated occupancy. Median estimated annual revenue nevertheless increased from approximately $33.0K for one-bedroom listings to $44.1K for two-bedroom listings and $47.5K for three-bedroom listings, suggesting higher nightly rates offset lower utilization. However, the revenue gain from two to three bedrooms was relatively modest despite a substantial increase in nightly price.
- The highest-priced neighborhoods are not necessarily the highest-revenue neighborhoods. Estimated revenue appears to depend on the interaction between nightly price and estimated occupancy.
- Revenue performance appears strongest when listings achieve a favorable balance between nightly price and utilization, rather than maximizing either one independently.
- Large/professional operators tend to command relatively high nightly prices without achieving correspondingly high estimated revenue. Their estimated occupancy is lower than single-listing and medium operators at every bedroom count.
- Among comparable short-stay entire homes/apartments, Superhost listings are associated with substantially higher estimated annual revenue across 1-, 2-, and 3-bedroom properties. The difference appears to be driven primarily by much higher estimated occupancy, with additional nightly-price advantages among 2- and 3-bedroom listings.
- Host portfolio size doesn't predict success cleanly, but Superhost status does show a strong association with estimated performance.
- Within established, highly rated listings, perfect 5.0 ratings are associated with higher estimated revenue, but not necessarily higher estimated occupancy.
- Among established, highly rated comparable listings, perfect 5.0-rated properties are associated with higher median estimated annual revenue across all three bedroom categories. The results suggest a price premium is part of this relationship, while 5.0 ratings do not consistently correspond to higher estimated occupancy.
- The 5.0 groups are much smaller and have substantially fewer reviews. For example, 1BR 5.0 listings have a median of 46 reviews versus 137 for 4.5–4.99 listings. So 5.0 shouldn't automatically be interpreted as superior operating performance.
- Among comparable short-stay entire homes/apartments, greater amenity richness is generally associated with higher estimated annual revenue. The pattern persists within bedroom categories and appears to reflect a combination of stronger nightly pricing and higher estimated utilization, particularly among listings with roughly 40–70+ amenities.
- Higher nightly prices are not uniformly associated with higher estimated annual revenue. Among comparable Denver short-stay listings, increasing price is generally accompanied by lower estimated occupancy, and several bedroom segments show a middle-to-upper price range where the combination of rate and utilization produces higher estimated revenue than still-more-expensive listings.
- Bedroom count affects pricing, price relates to occupancy, occupancy strongly affects revenue, and therefore revenue performance reflects the interaction between rate and utilization rather than either metric alone.

Host location category analysis
- Out-of-state hosts have the highest median estimated revenue. Their median estimated revenue is $44,709, compared with $39,652 for Denver-based hosts. However, they also have higher median nightly prices ($349.50 versus $267.33) and lower estimated occupancy (133 versus 161 nights). This suggests that out-of-state hosts may be following a higher-price, lower-utilization strategy.
- Denver-based hosts have the highest median estimated occupancy. At 161 nights, Denver-based hosts outperform the other visible categories in estimated occupancy. They also represent by far the largest segment, with 1,297 listings. This is an interesting finding because local hosts appear to achieve greater utilization without charging the highest nightly rates.
- Other Colorado hosts have the lowest median estimated revenue. Their median revenue is $23,756.50, substantially below both Denver and out-of-state hosts. But this does not necessarily mean these hosts are less effective. Differences in bedroom distribution, neighborhoods, property characteristics, and listing maturity could explain some of the gap.

Property category analysis 
- Property type matters even after controlling for bedroom count and stay policy. Median estimated revenue differs considerably between property categories.
- Price and occupancy can offset one another. Guesthouses generally have stronger estimated occupancy, whereas condos command higher nightly prices.
- Sample size matters. The 294 one-bedroom guesthouses provide a more substantial comparison group than the 11 three-bedroom condos.

Bathrooms analysis 
- Additional bathrooms are associated with a pricing premium within most bedroom categories.
- Higher nightly prices do not necessarily translate into proportionally higher estimated revenue, because estimated occupancy can be lower.
- The strongest revenue advantage appears among two-bedroom listings, where higher bathroom counts are associated with progressively higher median estimated revenue.

listing acitivty status analysis 
- Recently reviewed listings dominate estimated performance
- Recently reviewed listings have: The highest median nightly price ($236.78). The highest median estimated occupancy (175 nights). The highest median estimated annual revenue ($36,726).
- Their median estimated revenue is approximately 2.9 times that of listings reviewed within the last year but not within the last 30 days.
- This is a substantial difference, although it shouldn't automatically be interpreted as evidence that recent reviews cause higher occupancy.
- Zero estimated occupancy aligns perfectly with two activity categories.
- Every listing in the historically reviewed and never-reviewed categories has zero estimated occupancy in your filtered results.
- Conversely, every listing with a review within the last year has positive estimated occupancy.
- This is too systematic to treat as an ordinary market correlation.
- It strongly suggests that estimated_occupancy_l365d is derived using recent review activity, or at least depends on a related underlying measure.
- We haven't independently verified the dataset provider's methodology, so we shouldn't claim to know the exact formula yet.

hosts_time_as_host_years analysis
- Finding A: Hosts with 1–5 years of experience have the highest median estimated revenue across all three bedroom groups. The differences are substantial. However, this does not establish that gaining experience directly increases revenue. Newer hosts may have incomplete operating histories, different listing characteristics, or different review activity.
- Finding B: New hosts have the highest zero-occupancy percentages. The pattern is particularly pronounced for 3-bedroom listings, where 14.29% of listings hosted by people with less than one year of experience have zero modeled occupancy. The sample for this group is only 28 listings, so the percentage should be interpreted cautiously.
- Finding C: The relationship is not consistently linear beyond the first year. For 1-bedroom listings, hosts with more than 10 years of experience have higher median estimated occupancy than hosts with 1–5 years: Over 10 years: 203 days. 1–5 years: 196 days.
- However, their median estimated revenue is lower. This illustrates why occupancy and revenue need to be evaluated together. Higher modeled occupancy doesn't necessarily translate into higher modeled revenue when pricing differs. For 2- and 3-bedroom listings, the 1–5 year category has the highest median estimated revenue, but the relationships between tenure, price, and occupancy vary.
- Among comparable short-stay entire homes/apartments, hosts with 1–5 years of tenure have the highest median modeled annual revenue across all three bedroom groups. The association does not establish a causal benefit of host experience.

reviews_per_month_analysis
- Review frequency and estimated occupancy are strongly associated across several categories, but the occupancy metric may depend on review information.
- Estimated occupancy appears to have a ceiling of 255 days, which limits comparisons among higher-activity listings.

review_scores_location analysis
- Finding A: Location ratings remain consistently high. Even after excluding listings with fewer than 20 reviews, the highest-ranked neighborhoods have average ratings between approximately 4.92 and 4.98. This supports our earlier observation that location ratings are highly concentrated near the maximum of 5.0. The difference between Washington Park (4.98) and Highland (4.92) is just 0.06 points on a five-point scale. That may be statistically detectable in some circumstances, but it is not necessarily practically meaningful.
- Finding B: Some neighborhoods have stronger sample sizes
- Consider these two neighborhoods:
    - City Park: 11 qualifying listings, average location rating 4.97.
    - Union Station: 51 qualifying listings, average location rating 4.96.
- Although City Park ranks slightly higher, Union Station's result is based on substantially more listings. Likewise, Highland has 105 qualifying listings, giving us a broader representation of qualifying properties than neighborhoods with only 10–11. This doesn't automatically make the larger groups unbiased, but it makes their descriptive summaries less dependent on a handful of properties.
- Finding C: Mean and median ratings are similar. For many neighborhoods, average and median location ratings differ by only a few hundredths. This is consistent with ratings being tightly concentrated toward the upper end of the scale. However, mean and median alone cannot establish the full shape of the distribution. A boxplot in Python would make the spread easier to examine.

cleaned_calendar analysis
- Availability is lowest near the beginning of the calendar. July 2026 has an availability percentage of 31.26%, compared with approximately 62–67% in November and December 2026. This could reflect bookings, blocked dates, or the fact that dates closer to the scrape are more likely to have already been reserved. We cannot interpret this as proof that July has the highest demand.
- Availability rises later in 2026 November and December have the highest availability percentages in your results: November: 66.14% December: 66.55%
- This means approximately two-thirds of the observed listing-days were marked available. It does not mean these months had a 33–34% occupancy rate.
- Availability declines again in spring 2027. April, May, and June 2027 have availability percentages near 51%. That could reflect seasonal patterns, advance booking restrictions, or differences in how hosts manage future availability. We would need additional evidence to distinguish these explanations.
- Monthly-stay listings generally have higher future availability. From September 2026 through June 2027, monthly-stay listings consistently have a higher percentage of available listing-days than short-stay listings. The gap becomes particularly noticeable in spring 2027.
- Short-stay availability declines more sharply in spring 2027 Between March and April 2027: Short-stay availability falls from 58.36% to 45.57%. Monthly-stay availability falls from 64.91% to 56.08%.
- This suggests different future calendar availability patterns between the two stay policies. It does not necessarily mean short-stay properties will achieve higher occupancy. Unavailable dates can represent reservations, owner blocks, or other restrictions.
- The pattern reverses near the beginning of the calendar. In July and August 2026, short-stay listings actually have higher availability percentages.
- This is worth noting because the relationship between stay policy and availability isn't constant across the entire booking horizon.
- Business interpretation: Stay policy appears to be associated with differences in how hosts manage future availability, particularly further into the calendar. We cannot attribute the differences to demand alone.
- Availability differs substantially by neighborhood. Hale has 78.14% of its future listing-days available, compared with only 35.76% in Washington Park. That's a difference of 42.38 percentage points. This suggests that neighborhood is associated with meaningful differences in future calendar availability, even after restricting the analysis to comparable property types.
- High estimated revenue doesn't necessarily correspond to low availability. Earlier, we identified Five Points as a relatively strong neighborhood for estimated revenue.
- In this analysis, Five Points has: 143 qualifying listings, 53.22% future availability. Meanwhile, Highland has 133 listings and 62.92% availability.
- Both neighborhoods appeared competitive in our earlier revenue analysis, yet their future availability profiles differ.
- This reinforces an important distinction: Estimated annual revenue measures modeled historical performance, whereas calendar availability describes future bookable inventory. We should not interpret the unavailable percentage as an occupancy rate because blocked dates and booked dates are not distinguishable from this field alone.

cleaned_reviews analysis
- Review activity shows consistent seasonality. The strongest review activity generally occurs between June and September, while January, February, and December have substantially fewer reviews.
- 2023 peak: July, 5,873 reviews.
- 2024 peak: June, 6,532 reviews.
- 2025 peak: June, 7,009 reviews.
- This recurring pattern is stronger evidence of seasonality than examining any single year.
- Review volume increased across the three years. Nearly every month shows higher review volume in 2025 than in 2023.
- However, this does not necessarily mean Airbnb demand increased by the same proportion. The number of listings represented in the historical review data may have changed, and reviews are only an indirect indicator of guest activity.
- Reviews per reviewed listing also fluctuate seasonally For example, in 2023:
- January: 2.86 reviews per reviewed listing.
- July: 3.97.
- December: 2.44.
- This suggests the seasonal pattern is not explained solely by changes in the number of listings receiving reviews. Review frequency among those listings also varies.

## Does reviews per month have an effect on median price, median estimated occupancy, and median estimated revenue?

In [11]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified, hosts_time_as_host_years,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Does reviews per month have an effect on median price, median estimated occupancy, and median estimated revenue?


SELECT 
	CASE 
		WHEN reviews_per_month IS NULL THEN 'Missing'
		WHEN reviews_per_month < 1.00 THEN 'Under 1.00'
		WHEN reviews_per_month < 4.00 THEN '1.00-3.99'
		WHEN reviews_per_month < 7.00 THEN '4.00-6.99'
		WHEN reviews_per_month < 10.00 THEN '7.00-9.99'
		ELSE '10.00+'
	END AS reviews_per_month_category,
	COUNT(*) AS listings,
	ROUND(AVG(review_scores_rating), 2) AS avg_rating_score,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) AS zero_estimated_occupancy_values,
	ROUND(
    	COUNT(*) FILTER (
        WHERE estimated_occupancy_l365d = 255
    	) * 100.0 / COUNT(*),
    2) AS pct_at_occupancy_ceiling,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE cleaned_price IS NOT NULL AND estimated_revenue_l365d IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY reviews_per_month_category
ORDER BY listings DESC;

  reviews_per_month_category  ...  median_estimated_revenue
0                  1.00-3.99  ...                   40782.0
1                  4.00-6.99  ...                   54060.0
2                 Under 1.00  ...                   10878.0
3                  7.00-9.99  ...                   53040.0
4                    Missing  ...                       0.0
5                     10.00+  ...                   29725.0

[6 rows x 8 columns]

## Does avg_review_scores_location have significant differences by neighborhood?

In [12]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified, hosts_time_as_host_years,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How much does avg_review_scores_location differ by neighborhood?
	
SELECT 
	neighbourhood_cleansed,
	COUNT(*) AS listings,
	ROUND(AVG(number_of_reviews), 2) AS avg_reviews_per_qualified_listing,
	ROUND(AVG(review_scores_location), 2) AS avg_review_scores_location,
	MEDIAN(review_scores_location) AS median_review_scores_location
FROM cleaned_listings
WHERE room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
	AND number_of_reviews >= 20 
GROUP BY neighbourhood_cleansed
HAVING COUNT(*) >= 10
ORDER BY avg_review_scores_location DESC, listings DESC;

          neighbourhood_cleansed  ...  median_review_scores_location
0                Washington Park  ...                          4.980
1                      City Park  ...                          4.970
2                  Union Station  ...                          4.970
3                     Platt Park  ...                          4.980
4                     University  ...                          4.970
5                           Hale  ...                          4.970
6           Washington Park West  ...                          4.965
7                       Berkeley  ...                          4.950
8                  West Highland  ...                          4.970
9                     Sloan Lake  ...                          4.950
10                  Cherry Creek  ...                          4.960
11                 Congress Park  ...                          4.950
12                     Stapleton  ...                          4.945
13                      Highland  ...                          4.930
14                         Regis  ...                          4.910
15                         Speer  ...                          4.940
16               South Park Hill  ...                          4.910
17                     Sunnyside  ...                          4.935
18                       Skyland  ...                          4.910
19                Jefferson Park  ...                          4.925
20                  Capitol Hill  ...                          4.910
21               North Park Hill  ...                          4.910
22                           CBD  ...                          4.910
23                         Baker  ...                          4.895
24  Gateway - Green Valley Ranch  ...                          4.900
25              Virginia Village  ...                          4.905
26                  Civic Center  ...                          4.880
27                      Whittier  ...                          4.880
28            North Capitol Hill  ...                          4.850
29                City Park West  ...                          4.920
30                 Cheesman Park  ...                          4.940
31                   Five Points  ...                          4.880
32                          Cole  ...                          4.820
33                  Chaffee Park  ...                          4.830
34                   West Colfax  ...                          4.850
35                  Lincoln Park  ...                          4.820
36                       Clayton  ...                          4.830
37                   Athmar Park  ...                          4.770
38                     Ruby Hill  ...                          4.700
39                    Villa Park  ...                          4.740
40                      Valverde  ...                          4.715
41                   East Colfax  ...                          4.755

[42 rows x 5 columns]

## Does time as host (years) impact median price, median estimated occupancy, or median estimated revenue?

In [4]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified, hosts_time_as_host_years,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Does time as host (years) impact median price, median estimated occupancy, or median estimated revenue?
	
SELECT 
	CASE 
		WHEN hosts_time_as_host_years < 1 THEN 'Less Than 1 Year'
		WHEN hosts_time_as_host_years BETWEEN 1 AND 5 THEN '1-5 Years'
		WHEN hosts_time_as_host_years BETWEEN 6 AND 10 THEN '6-10 Years'
		ELSE 'Over 10 Years'
	END AS category_hosts_time_as_host_years,
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) AS zero_estimated_occupancy_listing,
	ROUND(
    SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END)
    * 100.0 / COUNT(*),
    2
) AS pct_zero_estimated_occupancy
FROM cleaned_listings
WHERE cleaned_price IS NOT NULL and hosts_time_as_host_years IS NOT NULL AND estimated_revenue_l365d IS NOT NULL
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY category_hosts_time_as_host_years, bedrooms
ORDER BY bedrooms, category_hosts_time_as_host_years;

   category_hosts_time_as_host_years  ...  pct_zero_estimated_occupancy
0                          1-5 Years  ...                          1.04
1                         6-10 Years  ...                          1.85
2                   Less Than 1 Year  ...                          8.16
3                      Over 10 Years  ...                          0.00
4                          1-5 Years  ...                          3.53
5                         6-10 Years  ...                          1.42
6                   Less Than 1 Year  ...                         10.17
7                      Over 10 Years  ...                          6.52
8                          1-5 Years  ...                          3.82
9                         6-10 Years  ...                          0.00
10                  Less Than 1 Year  ...                         14.29
11                     Over 10 Years  ...                          8.11

[12 rows x 8 columns]

## How does monthly review activity change over time in Denver, and are there noticeable seasonal patterns?

In [36]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does monthly review activity change over time in Denver, and are there noticeable seasonal patterns?

SELECT 
	year_month,
	year,
	month,
	COUNT(*) AS reviews,
	COUNT(DISTINCT listing_id) AS reviewed_listings,
	ROUND(COUNT(*) * 1.0 / COUNT(DISTINCT listing_id), 2) AS avg_reviews_per_reviewed_listing
FROM cleaned_reviews
WHERE review_id IS NOT NULL AND listing_id IS NOT NULL AND year_month IS NOT NULL AND year BETWEEN 2023 AND 2025
GROUP BY year_month, year, month
ORDER BY month, year;

                  year_month  ...  avg_reviews_per_reviewed_listing
0  2023-01-01 00:00:00+00:00  ...                              2.86
1  2024-01-01 00:00:00+00:00  ...                              2.60
2  2025-01-01 00:00:00+00:00  ...                              2.46
3  2023-02-01 00:00:00+00:00  ...                              2.99
4  2024-02-01 00:00:00+00:00  ...                              2.72
5  2025-02-01 00:00:00+00:00  ...                              2.53
6  2023-03-01 00:00:00+00:00  ...                              3.25
7  2024-03-01 00:00:00+00:00  ...                              2.94
8  2025-03-01 00:00:00+00:00  ...                              2.74
9  2023-04-01 00:00:00+00:00  ...                              3.32
10 2024-04-01 00:00:00+00:00  ...                              3.07
11 2025-04-01 00:00:00+00:00  ...                              2.86
12 2023-05-01 00:00:00+00:00  ...                              3.57
13 2024-05-01 00:00:00+00:00  ...                              3.32
14 2025-05-01 00:00:00+00:00  ...                              3.06
15 2023-06-01 00:00:00+00:00  ...                              3.83
16 2024-06-01 00:00:00+00:00  ...                              3.81
17 2025-06-01 00:00:00+00:00  ...                              3.68
18 2023-07-01 00:00:00+00:00  ...                              3.97
19 2024-07-01 00:00:00+00:00  ...                              3.57
20 2025-07-01 00:00:00+00:00  ...                              3.41
21 2023-08-01 00:00:00+00:00  ...                              3.38
22 2024-08-01 00:00:00+00:00  ...                              3.44
23 2025-08-01 00:00:00+00:00  ...                              3.21
24 2023-09-01 00:00:00+00:00  ...                              3.64
25 2024-09-01 00:00:00+00:00  ...                              3.66
26 2025-09-01 00:00:00+00:00  ...                              3.41
27 2023-10-01 00:00:00+00:00  ...                              3.66
28 2024-10-01 00:00:00+00:00  ...                              3.16
29 2025-10-01 00:00:00+00:00  ...                              3.16
30 2023-11-01 00:00:00+00:00  ...                              2.73
31 2024-11-01 00:00:00+00:00  ...                              2.55
32 2025-11-01 00:00:00+00:00  ...                              2.61
33 2023-12-01 00:00:00+00:00  ...                              2.44
34 2024-12-01 00:00:00+00:00  ...                              2.44
35 2025-12-01 00:00:00+00:00  ...                              2.39

[36 rows x 6 columns]

## Which Denver neighborhoods have the highest and lowest future calendar availability among comparable short-stay entire homes/apartments?

In [31]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month,
		l.neighbourhood_cleansed,
		l.room_type,
		l.bedrooms,
		l.stay_policy
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Which Denver neighborhoods have the highest and lowest future calendar availability among comparable short-stay entire homes/apartments?

SELECT 
	neighbourhood_cleansed,
	COUNT(DISTINCT listing_id) AS listings,
	COUNT(*) AS listing_days,
	SUM(CASE WHEN available IS TRUE THEN 1 ELSE 0 END) AS available_listing_days,
	SUM(CASE WHEN available IS FALSE THEN 1 ELSE 0 END) AS unavailable_listing_days,
	ROUND(SUM(CASE WHEN available IS TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS pct_of_listing_days_available
FROM cleaned_calendar
WHERE year_month >= DATE '2026-07-01'
	AND year_month < DATE '2027-07-01'
	AND available IS NOT NULL
	AND date IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY neighbourhood_cleansed
HAVING COUNT(DISTINCT listing_id) >= 20
ORDER BY pct_of_listing_days_available DESC;

          neighbourhood_cleansed  ...  pct_of_listing_days_available
0                           Hale  ...                          78.14
1                   Civic Center  ...                          71.32
2   Gateway - Green Valley Ranch  ...                          70.05
3               Virginia Village  ...                          64.51
4                       Highland  ...                          62.92
5                 Jefferson Park  ...                          58.32
6                 City Park West  ...                          57.17
7                      Stapleton  ...                          55.70
8                      Sunnyside  ...                          55.44
9                          Speer  ...                          54.01
10                 Cheesman Park  ...                          53.76
11                         Baker  ...                          53.32
12                   Five Points  ...                          53.22
13                      Whittier  ...                          51.66
14                  Cherry Creek  ...                          51.21
15          Washington Park West  ...                          50.97
16                 West Highland  ...                          49.45
17                 Union Station  ...                          49.14
18                      Berkeley  ...                          48.86
19                   West Colfax  ...                          48.33
20                    Platt Park  ...                          48.06
21                  Lincoln Park  ...                          47.02
22                       Clayton  ...                          46.63
23                 Congress Park  ...                          46.47
24                       Skyland  ...                          44.41
25                          Cole  ...                          44.20
26                   Athmar Park  ...                          44.15
27                    Sloan Lake  ...                          43.71
28               North Park Hill  ...                          41.31
29                  Capitol Hill  ...                          40.41
30               Washington Park  ...                          35.76

[31 rows x 6 columns]

## How does monthly calendar availability differ between short-stay and monthly-stay Denver Airbnb listings?

In [29]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month,
		l.stay_policy
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does monthly calendar availability differ between short-stay and monthly-stay Denver Airbnb listings?

SELECT 
	year_month,
	stay_policy,
	COUNT(*) AS listing_days,
	SUM(CASE WHEN available IS TRUE THEN 1 ELSE 0 END) AS available_listing_days,
	ROUND(SUM(CASE WHEN available IS TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS pct_of_listing_days_available
FROM cleaned_calendar 
WHERE stay_policy IN ('Short stay', 'Monthly stay')
  AND year_month >= DATE '2026-07-01'
  AND year_month < DATE '2027-07-01'
  AND available IS NOT NULL
  AND date IS NOT NULL
GROUP BY year_month, stay_policy
ORDER BY year_month, stay_policy;

                  year_month  ... pct_of_listing_days_available
0  2026-07-01 00:00:00+00:00  ...                         26.86
1  2026-07-01 00:00:00+00:00  ...                         34.87
2  2026-08-01 00:00:00+00:00  ...                         50.69
3  2026-08-01 00:00:00+00:00  ...                         52.97
4  2026-09-01 00:00:00+00:00  ...                         63.28
5  2026-09-01 00:00:00+00:00  ...                         59.93
6  2026-10-01 00:00:00+00:00  ...                         63.31
7  2026-10-01 00:00:00+00:00  ...                         60.40
8  2026-11-01 00:00:00+00:00  ...                         67.37
9  2026-11-01 00:00:00+00:00  ...                         64.66
10 2026-12-01 00:00:00+00:00  ...                         67.72
11 2026-12-01 00:00:00+00:00  ...                         65.16
12 2027-01-01 00:00:00+00:00  ...                         64.46
13 2027-01-01 00:00:00+00:00  ...                         59.65
14 2027-02-01 00:00:00+00:00  ...                         65.49
15 2027-02-01 00:00:00+00:00  ...                         60.28
16 2027-03-01 00:00:00+00:00  ...                         64.91
17 2027-03-01 00:00:00+00:00  ...                         58.36
18 2027-04-01 00:00:00+00:00  ...                         56.08
19 2027-04-01 00:00:00+00:00  ...                         45.57
20 2027-05-01 00:00:00+00:00  ...                         56.89
21 2027-05-01 00:00:00+00:00  ...                         45.58
22 2027-06-01 00:00:00+00:00  ...                         56.11
23 2027-06-01 00:00:00+00:00  ...                         44.77

[24 rows x 5 columns]

## How does the percentage of available Airbnb listing-days vary by month in Denver?

In [27]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does the percentage of available Airbnb listing-days vary by month in Denver?

SELECT 
	year_month,
	COUNT(*) AS listing_days,
	SUM(CASE WHEN available IS TRUE THEN 1 ELSE 0 END) AS available_listing_days,
	SUM(CASE WHEN available IS FALSE THEN 1 ELSE 0 END) AS unavailable_listing_days,
	ROUND(SUM(CASE WHEN available IS TRUE THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS pct_of_listing_days_available
FROM cleaned_calendar
WHERE available IS NOT NULL AND date IS NOT NULL
GROUP BY year_month
ORDER BY year_month;

                  year_month  ...  pct_of_listing_days_available
0  2026-06-01 00:00:00+00:00  ...                          15.87
1  2026-07-01 00:00:00+00:00  ...                          31.26
2  2026-08-01 00:00:00+00:00  ...                          51.95
3  2026-09-01 00:00:00+00:00  ...                          61.62
4  2026-10-01 00:00:00+00:00  ...                          62.04
5  2026-11-01 00:00:00+00:00  ...                          66.14
6  2026-12-01 00:00:00+00:00  ...                          66.55
7  2027-01-01 00:00:00+00:00  ...                          62.17
8  2027-02-01 00:00:00+00:00  ...                          63.04
9  2027-03-01 00:00:00+00:00  ...                          61.81
10 2027-04-01 00:00:00+00:00  ...                          51.00
11 2027-05-01 00:00:00+00:00  ...                          51.46
12 2027-06-01 00:00:00+00:00  ...                          50.73
13 2027-07-01 00:00:00+00:00  ...                          15.93

[14 rows x 5 columns]

## How does listing activity status relate to median nightly price, median estimated occupancy, and median estimated annual revenue among Denver Airbnb listings?

In [23]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does listing activity status relate to median nightly price, median estimated occupancy, and median estimated annual revenue among Denver Airbnb listings?

SELECT
	listing_activity_status,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue,
	SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) AS zero_occupancy_listings
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL
GROUP BY listing_activity_status
ORDER BY median_estimated_revenue DESC;

  listing_activity_status  ...  zero_occupancy_listings
0       Recently Reviewed  ...                      0.0
1   Reviewed in Last Year  ...                      0.0
2          Never Reviewed  ...                    517.0
3   Historically Reviewed  ...                    495.0

[4 rows x 6 columns]

## Among comparable 1–3 bedroom short-stay entire homes/apartments, how does bathroom type relate to median nightly price, median estimated occupancy, and median estimated annual revenue?

In [19]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how does bathroom type relate to median nightly price, median estimated occupancy, and median estimated annual revenue?
-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how does the number of bathrooms relate to median nightly price, median estimated occupancy, and median estimated annual revenue?

SELECT 
	bedrooms,
	bathrooms,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL AND bathrooms IS NOT NULL
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY bedrooms, bathrooms
HAVING COUNT(*) >= 10
ORDER BY bedrooms, bathrooms;

    bedrooms  bathrooms  ...  median_estimated_occupancy  median_estimated_revenue
0          1        1.0  ...                       175.0                   33214.0
1          1        1.5  ...                       126.0                   34793.5
2          2        1.0  ...                       168.0                   39266.5
3          2        1.5  ...                       108.5                   42098.0
4          2        2.0  ...                       126.0                   46826.5
5          2        2.5  ...                       122.5                   53598.5
6          3        1.0  ...                       157.5                   48263.0
7          3        1.5  ...                       105.0                   43292.0
8          3        2.0  ...                       112.0                   45360.0
9          3        2.5  ...                        98.0                   47748.5
10         3        3.0  ...                        98.0                   51563.5
11         3        3.5  ...                        98.0                   47677.0

[12 rows x 6 columns]

## How do different Denver Airbnb property categories compare in listing count, median nightly price, median estimated occupancy, and median estimated annual revenue?

In [14]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Specialty/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How do different Denver Airbnb property categories compare in listing count, median nightly price, median estimated occupancy, and median estimated annual revenue?
-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how do property categories differ in median nightly price, median estimated occupancy, and median estimated annual revenue?

SELECT 
	property_category,
	bedrooms,
	COUNT(*) AS listings,
	COUNT(DISTINCT host_id) AS hosts,
	ROUND(COUNT(*) / COUNT(DISTINCT host_id), 2) AS listings_per_host,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY property_category, bedrooms
HAVING COUNT(*) >= 10
ORDER BY bedrooms, median_estimated_revenue DESC;

        property_category  ...  median_estimated_revenue
0                   Condo  ...                   43740.0
1              Guesthouse  ...                   36288.0
2               Townhouse  ...                   32280.5
3              House/Home  ...                   30542.5
4   Apartment/Rental Unit  ...                   25813.5
5                   Condo  ...                   70980.0
6               Townhouse  ...                   48089.0
7              Guesthouse  ...                   42023.5
8   Apartment/Rental Unit  ...                   40800.0
9              House/Home  ...                   36200.5
10                  Condo  ...                   90552.0
11  Apartment/Rental Unit  ...                   59109.0
12             House/Home  ...                   47208.5
13              Townhouse  ...                   45772.0

[14 rows x 8 columns]

## How do host location categories differ in listing count, median nightly price, median estimated occupancy, and median estimated annual revenue?

In [6]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

SELECT 
	host_location_category,
	COUNT(DISTINCT host_id) AS hosts,
	COUNT(*) AS listings,
	SUM(CASE WHEN host_scale = 'Single-listing host' THEN 1 ELSE 0 END) AS single_host_listings,
	SUM(CASE WHEN host_scale = 'Small multi-listing host' THEN 1 ELSE 0 END) AS small_multi_host_listings,
	SUM(CASE WHEN host_scale = 'Medium operator' THEN 1 ELSE 0 END) AS medium_operator_listings,
	SUM(CASE WHEN host_scale = 'Large/professional operator' THEN 1 ELSE 0 END) AS large_professional_operator_listings
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL
GROUP BY host_location_category
ORDER BY listings DESC;

  host_location_category  ...  large_professional_operator_listings
0                 Denver  ...                                 403.0
1            No Location  ...                                 189.0
2         Other Colorado  ...                                  55.0
3         Other US State  ...                                  60.0
4          Other Country  ...                                   0.0

[5 rows x 7 columns]

In [5]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How do host location categories differ in listing count, median nightly price, median estimated occupancy, and median estimated annual revenue?

SELECT 
	host_location_category,
	COUNT(DISTINCT host_id) AS hosts,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY host_location_category
ORDER BY median_estimated_revenue DESC;

  host_location_category  ...  median_estimated_revenue
0         Other US State  ...                   44709.0
1                 Denver  ...                   39652.0
2            No Location  ...                   32258.0
3          Other Country  ...                   28700.0
4         Other Colorado  ...                   23756.5

[5 rows x 6 columns]

## Which combinations of neighborhood and bedroom count appear to offer the strongest balance of median estimated revenue and median estimated occupancy among comparable short-stay entire homes/apartments?

In [166]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Which combinations of neighborhood and bedroom count appear to offer the strongest balance of median estimated revenue and median estimated occupancy among comparable short-stay entire homes/apartments?

SELECT 
	neighbourhood_cleansed,
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY neighbourhood_cleansed, bedrooms
HAVING COUNT(*) >= 20
ORDER BY bedrooms, median_estimated_revenue DESC;

   neighbourhood_cleansed  ...  median_estimated_revenue
0             Five Points  ...                   45479.0
1                Highland  ...                   44478.0
2                   Speer  ...                   41668.0
3              Platt Park  ...                   36920.5
4               Sunnyside  ...                   34639.0
5              Sloan Lake  ...                   34346.0
6           Union Station  ...                   33124.0
7                Whittier  ...                   32318.0
8             West Colfax  ...                   30903.0
9                Berkeley  ...                   29029.0
10           Civic Center  ...                   16979.0
11                   Hale  ...                    5224.0
12          Union Station  ...                   81708.0
13            Five Points  ...                   71145.0
14               Berkeley  ...                   47712.0
15               Highland  ...                   46172.0
16            West Colfax  ...                   45500.0
17              Sunnyside  ...                   45036.0
18            Five Points  ...                   79800.0
19               Highland  ...                   59925.0

[20 rows x 6 columns]

## Among comparable 1–3 bedroom short-stay entire homes/apartments, how does nightly price relate to estimated annual revenue?

In [161]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how does nightly price relate to estimated annual revenue?

SELECT 
	bedrooms,
	CASE 
		WHEN cleaned_price < 100 THEN '< $100'
		WHEN cleaned_price < 200 THEN '$100-199'
		WHEN cleaned_price < 300 THEN '$200-299'
		WHEN cleaned_price < 400 THEN '$300-399'
		WHEN cleaned_price < 500 THEN '$400-499'
		WHEN cleaned_price < 750 THEN '$500-749'
		WHEN cleaned_price < 1000 THEN '$749-999'
	ELSE '$1,000+'
	END AS price_category,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY bedrooms, price_category
HAVING COUNT(*) >= 10
ORDER BY bedrooms, median_estimated_revenue DESC;

    bedrooms  ... median_estimated_revenue
0          1  ...                  46168.5
1          1  ...                  40243.0
2          1  ...                  36498.0
3          1  ...                  28922.0
4          2  ...                  62524.0
5          2  ...                  55559.0
6          2  ...                  50328.5
7          2  ...                  38903.0
8          2  ...                  31692.0
9          3  ...                  73983.0
10         3  ...                  70789.5
11         3  ...                  65050.0
12         3  ...                  60971.5
13         3  ...                  36414.5
14         3  ...                  36295.0

[15 rows x 6 columns]

## Among comparable 1–3 bedroom short-stay entire homes/apartments, how does amenity richness relate to estimated annual revenue?

In [156]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how does amenity richness relate to estimated annual revenue?

SELECT 
	bedrooms,
	CASE 
		WHEN amenity_count <= 10 THEN '10 or Less Amenities'
		WHEN amenity_count <= 20 THEN '11-20 Amenities'
		WHEN amenity_count <= 30 THEN '21-30 Amenities'
		WHEN amenity_count <= 40 THEN '31-40 Amenities' 
		WHEN amenity_count <= 50 THEN '41-50 Amenities'
		WHEN amenity_count <= 60 THEN '51-60 Amenities'
		WHEN amenity_count <= 70 THEN '61-70 Amenities'
		WHEN amenity_count <= 80 THEN '71-80 Amenities'
		ELSE 'Over 80 Amenities'
	END AS amenity_count_category,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings 
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY bedrooms, amenity_count_category
HAVING COUNT(*) >= 10
ORDER BY bedrooms, median_estimated_revenue DESC;

    bedrooms  ... median_estimated_revenue
0          1  ...                  42252.0
1          1  ...                  35700.0
2          1  ...                  34713.0
3          1  ...                  28258.0
4          1  ...                  21111.0
5          1  ...                  13790.0
6          2  ...                  51786.0
7          2  ...                  50944.0
8          2  ...                  46921.0
9          2  ...                  40163.0
10         2  ...                  36736.0
11         2  ...                  19527.0
12         2  ...                   7652.0
13         3  ...                  82131.5
14         3  ...                  61182.0
15         3  ...                  54292.0
16         3  ...                  38248.0
17         3  ...                  22127.0

[18 rows x 6 columns]

## Among comparable 1–3 bedroom short-stay entire homes/apartments, how do guest ratings relate to estimated annual revenue?

In [155]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how do guest ratings relate to estimated annual revenue?
	
SELECT 
	CASE 
		WHEN review_scores_rating < 4 THEN '<4.0'
		WHEN review_scores_rating <= 4.49 THEN '4.0-4.49'
		WHEN review_scores_rating <= 4.99 THEN '4.5-4.99'
		ELSE '5.0'
	END AS rating_category,
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(number_of_reviews) AS median_number_of_reviews,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE review_scores_rating IS NOT NULL AND number_of_reviews >= 20 
	AND estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY rating_category, bedrooms
HAVING COUNT(*) >= 10
ORDER BY bedrooms, median_estimated_revenue DESC;

  rating_category  ...  median_estimated_revenue
0             5.0  ...                   45850.0
1        4.5-4.99  ...                   36995.0
2             5.0  ...                   57036.0
3        4.5-4.99  ...                   51507.0
4             5.0  ...                   68607.0
5        4.5-4.99  ...                   61612.5

[6 rows x 7 columns]

## Among comparable 1–3 bedroom short-stay entire homes/apartments, how does Superhost status relate to estimated annual revenue?

In [149]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how does Superhost status relate to estimated annual revenue?

SELECT 
	host_is_superhost,
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY host_is_superhost, bedrooms
ORDER BY bedrooms, median_estimated_revenue DESC;

   host_is_superhost  ...  median_estimated_revenue
0               True  ...                   35758.0
1              False  ...                   17563.0
2               True  ...                   49470.0
3              False  ...                   17150.0
4               True  ...                   59925.0
5              False  ...                   18806.0

[6 rows x 6 columns]

## Among comparable 1–3 bedroom short-stay entire homes/apartments, how does host scale relate to estimated annual revenue?

In [148]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how does host scale relate to estimated annual revenue
-- Within comparable bedroom counts, do differences in estimated revenue by host scale persist?

host_scale_revenue_analysis AS (
	SELECT 
		host_scale,
		bedrooms,
		COUNT(*) AS listings,
		MEDIAN(cleaned_price) AS median_price,
		MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
		MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
	FROM cleaned_listings
	WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
		AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
	GROUP BY host_scale, bedrooms
)

SELECT 
	bedrooms,
	MAX(CASE WHEN host_scale = 'Single-listing host' THEN median_estimated_revenue END) AS single_median_estimated_revenue,
	MAX(CASE WHEN host_scale = 'Small multi-listing host' THEN median_estimated_revenue END) AS small_multi_median_estimated_revenue,
	MAX(CASE WHEN host_scale = 'Medium operator' THEN median_estimated_revenue END) AS medium_median_estimated_revenue,
	MAX(CASE WHEN host_scale = 'Large/professional operator' THEN median_estimated_revenue END) AS large_pro_median_estimated_revenue
FROM host_scale_revenue_analysis
GROUP BY bedrooms
ORDER BY bedrooms;

   bedrooms  ...  large_pro_median_estimated_revenue
0         1  ...                             16712.5
1         2  ...                             44730.0
2         3  ...                             46527.5

[3 rows x 5 columns]

## How does estimated annual revenue differ across the major types of Denver Airbnb listings?

In [142]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among comparable 1–3 bedroom short-stay entire homes/apartments, which Denver neighborhoods generate the highest and lowest estimated annual revenue?

SELECT 
	neighbourhood_cleansed,
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY neighbourhood_cleansed, bedrooms
HAVING COUNT(*) >= 20
ORDER BY bedrooms, median_estimated_revenue DESC;

   neighbourhood_cleansed  ...  median_estimated_revenue
0             Five Points  ...                   45479.0
1                Highland  ...                   44478.0
2                   Speer  ...                   41668.0
3              Platt Park  ...                   36920.5
4               Sunnyside  ...                   34639.0
5              Sloan Lake  ...                   34346.0
6           Union Station  ...                   33124.0
7                Whittier  ...                   32318.0
8             West Colfax  ...                   30903.0
9                Berkeley  ...                   29029.0
10           Civic Center  ...                   16979.0
11                   Hale  ...                    5224.0
12          Union Station  ...                   81708.0
13            Five Points  ...                   71145.0
14               Berkeley  ...                   47712.0
15               Highland  ...                   46172.0
16            West Colfax  ...                   45500.0
17              Sunnyside  ...                   45036.0
18            Five Points  ...                   79800.0
19               Highland  ...                   59925.0

[20 rows x 6 columns]

In [135]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among comparable 1–3 bedroom short-stay entire homes/apartments, how does estimated annual revenue differ by bedroom count?

SELECT 
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	MEDIAN(estimated_revenue_l365d) AS median_estimated_revenue
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL 
	AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY bedrooms
ORDER BY bedrooms;

   bedrooms  listings  ...  median_estimated_occupancy  median_estimated_revenue
0         1       706  ...                       168.0                   33036.5
1         2       572  ...                       147.0                   44072.5
2         3       338  ...                       112.0                   47516.5

[3 rows x 5 columns]

In [134]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does estimated annual revenue differ across the major types of Denver Airbnb listings?

SELECT 
	CASE 
		WHEN estimated_revenue_l365d < 1000 THEN '< $1,000'
		WHEN estimated_revenue_l365d < 10000 THEN '$1,000 - $9,999'
		WHEN estimated_revenue_l365d < 40000 THEN '$10,000 - $39,999'
		WHEN estimated_revenue_l365d < 70000 THEN '$40,000 - $69,999'
		WHEN estimated_revenue_l365d < 100000 THEN '$70,000 - $99,999'
		WHEN estimated_revenue_l365d < 200000 THEN '$100,000 - $199,999'
		ELSE '$200,000+'
	END AS estimated_revenue_category,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price,
	ROUND(AVG(cleaned_price), 2) AS avg_price,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy,
	SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) AS zero_occupancy_listings
FROM cleaned_listings
WHERE estimated_revenue_l365d IS NOT NULL AND cleaned_price IS NOT NULL
GROUP BY estimated_revenue_category
ORDER BY median_price DESC;

  estimated_revenue_category  ...  zero_occupancy_listings
0                  $200,000+  ...                      0.0
1        $100,000 - $199,999  ...                      0.0
2          $70,000 - $99,999  ...                      0.0
3          $40,000 - $69,999  ...                      0.0
4          $10,000 - $39,999  ...                      0.0
5                   < $1,000  ...                   1012.0
6            $1,000 - $9,999  ...                      0.0

[7 rows x 7 columns]

In [131]:
SELECT *
FROM 'detailed_listings.csv'
WHERE estimated_occupancy_l365d > 0 AND estimated_revenue_l365d < 1000;

                     id  ... reviews_per_month
0              12133753  ...              0.62
1              28545099  ...              0.61
2              29485829  ...              0.05
3              39914868  ...              1.12
4    891587185106153385  ...              0.13
5   1501170273263791470  ...              1.00
6   1545631957466578381  ...              0.17
7   1628268153237777464  ...              1.00
8   1639896230914418305  ...              1.00
9   1692187052209305838  ...              1.82
10  1667801024232219979  ...              1.00

[11 rows x 90 columns]

## How does host scale relate to estimated occupancy among comparable short-stay entire homes/apartments?

In [113]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does host scale relate to estimated occupancy among comparable short-stay entire homes/apartments?

SELECT 
	host_scale,
	COUNT(*) AS listings,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy,
	SUM(CASE
    WHEN estimated_occupancy_l365d = 0 THEN 1
    ELSE 0
	END) AS zero_occupancy_listings,
	ROUND(
    	SUM(CASE
       		WHEN estimated_occupancy_l365d = 0 THEN 1
        	ELSE 0
    	END) * 100.0 / COUNT(*),
    2) AS pct_zero_occupancy
FROM cleaned_listings
WHERE room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY host_scale
ORDER BY median_estimated_occupancy DESC;

                    host_scale  ...  pct_zero_occupancy
0          Single-listing host  ...                3.87
1              Medium operator  ...                1.23
2     Small multi-listing host  ...                6.87
3  Large/professional operator  ...                6.80

[4 rows x 6 columns]

## How do guest ratings relate to estimated occupancy?

In [110]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How do guest ratings relate to estimated occupancy?
-- Do perfect-5.0 listings have fewer reviews than listings rated 4.5–4.99?
-- Among listings with comparable review histories, do higher-rated listings tend to have higher estimated occupancy?

SELECT 
	CASE 
		WHEN review_scores_rating < 4 THEN '<4.0'
		WHEN review_scores_rating <= 4.49 THEN '4.0-4.49'
		WHEN review_scores_rating <= 4.99 THEN '4.5-4.99'
		ELSE '5.0'
	END AS rating_category,
	COUNT(*) AS listings,
	MEDIAN(number_of_reviews) AS median_number_of_reviews,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy
FROM cleaned_listings
WHERE review_scores_rating IS NOT NULL AND number_of_reviews >= 20
GROUP BY rating_category
ORDER BY median_estimated_occupancy DESC;

  rating_category  ...  avg_estimated_occupancy
0        4.5-4.99  ...                   153.31
1             5.0  ...                   150.00
2        4.0-4.49  ...                    58.86

[3 rows x 5 columns]

## Do Superhosts achieve higher estimated occupancy than non-Superhosts for comparable listings?

In [99]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Do Superhosts achieve higher estimated occupancy than non-Superhosts for comparable listings?
-- Within comparable 1–3 bedroom short-stay entire homes/apartments, how does estimated occupancy differ between Superhosts and non-Superhosts?

SELECT 
	host_is_superhost,
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy,
	SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) AS zero_occupancy_listings,
	ROUND(SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS zero_occupancy_percentage
FROM cleaned_listings
WHERE room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP BY host_is_superhost, bedrooms
ORDER BY host_is_superhost, bedrooms;

   host_is_superhost  ...  zero_occupancy_percentage
0              False  ...                       8.00
1              False  ...                      13.37
2              False  ...                      12.62
3               True  ...                       1.72
4               True  ...                       2.46
5               True  ...                       3.10

[6 rows x 7 columns]

## How does nightly price relate to estimated occupancy?

In [97]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does nightly price relate to estimated occupancy?
-- Within comparable short-stay entire homes/apartments of the same bedroom size, how does nightly price vary across estimated occupancy levels?

SELECT 
	CASE 
		WHEN estimated_occupancy_l365d = 0 THEN '0 Days'
		WHEN estimated_occupancy_l365d <= 50 THEN '1-50 Days'
		WHEN estimated_occupancy_l365d <= 100 THEN '51-100 Days'
		WHEN estimated_occupancy_l365d <= 150 THEN '101-150 Days'
		WHEN estimated_occupancy_l365d <= 200 THEN '151-200 Days'
		ELSE 'Over 200 Days'
	END AS estimated_occupancy_category,
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price
FROM cleaned_listings
WHERE cleaned_price IS NOT NULL AND room_type = 'Entire home/apt' AND stay_policy = 'Short stay' AND bedrooms BETWEEN 1 AND 3
GROUP by estimated_occupancy_category, bedrooms
ORDER BY estimated_occupancy_category, bedrooms;

   estimated_occupancy_category  bedrooms  listings  median_price
0                        0 Days         1        16        262.10
1                        0 Days         2        21        283.97
2                        0 Days         3        13        417.00
3                     1-50 Days         1       116        216.10
4                     1-50 Days         2        95        302.00
5                     1-50 Days         3        82        403.00
6                  101-150 Days         1        94        225.41
7                  101-150 Days         2        87        330.50
8                  101-150 Days         3        51        411.00
9                  151-200 Days         1       109        189.67
10                 151-200 Days         2        72        290.70
11                 151-200 Days         3        51        440.02
12                  51-100 Days         1        75        227.00
13                  51-100 Days         2        91        330.00
14                  51-100 Days         3        61        471.50
15                Over 200 Days         1       296        197.40
16                Over 200 Days         2       206        280.42
17                Over 200 Days         3        80        441.50

## Among comparable short-stay entire homes/apartments, which Denver neighborhoods have the highest and lowest estimated occupancy?

In [88]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among comparable short-stay entire homes/apartments, which Denver neighborhoods have the highest and lowest estimated occupancy?

SELECT 
	neighbourhood_cleansed,
	bedrooms,
	COUNT(*) AS listings,
	SUM(COUNT(*)) OVER (PARTITION BY neighbourhood_cleansed) AS total_comparable_neighbourhood_listings,
 	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy,
	SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) AS zero_estimated_occupancy_listings,
	ROUND(SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS pct_zero_occupancy
FROM cleaned_listings 
WHERE room_type = 'Entire home/apt'
  AND stay_policy = 'Short stay'
  AND bedrooms BETWEEN 1 AND 3
GROUP BY neighbourhood_cleansed, bedrooms
HAVING COUNT(*) >= 20
ORDER BY bedrooms, avg_estimated_occ;

   neighbourhood_cleansed  ...  pct_zero_occupancy
0                   Speer  ...                4.55
1             Five Points  ...                3.92
2              Platt Park  ...                0.00
3              Sloan Lake  ...                4.76
4                Whittier  ...                0.00
5               Sunnyside  ...                0.00
6           West Highland  ...                8.33
7                Berkeley  ...                7.89
8             West Colfax  ...                3.33
9                Highland  ...                1.69
10          Union Station  ...                2.94
11           Civic Center  ...                0.00
12                   Hale  ...               13.33
13            Five Points  ...                5.66
14          Union Station  ...                3.03
15               Berkeley  ...                2.94
16              Sunnyside  ...               11.11
17            West Colfax  ...                6.45
18         Jefferson Park  ...                4.76
19               Highland  ...                0.00
20            Five Points  ...                7.69
21               Highland  ...                7.41

[22 rows x 8 columns]

## Which Denver neighborhoods have the highest and lowest estimated occupancy?

In [84]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Which Denver neighborhoods have the highest and lowest estimated occupancy?

SELECT 
	neighbourhood_cleansed,
	COUNT(*) AS listings,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy,
	SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) AS zero_estimated_occupancy_listings,
	ROUND(
		SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 
	2) AS pct_zero_occupancy
FROM cleaned_listings
GROUP BY neighbourhood_cleansed
HAVING COUNT(*) >= 20
ORDER BY avg_estimated_occupancy;

          neighbourhood_cleansed  ...  pct_zero_occupancy
0                        Hampden  ...               38.46
1                  Hampden South  ...               40.63
2                      Montclair  ...               34.48
3                      Goldsmith  ...               52.00
4   Gateway - Green Valley Ranch  ...               43.88
5                    Athmar Park  ...               40.91
6                   Cherry Creek  ...               28.36
7               University Hills  ...               40.00
8                            DIA  ...               40.74
9                   Civic Center  ...               11.90
10            North Capitol Hill  ...               41.51
11                     Stapleton  ...               30.00
12                           CBD  ...               38.18
13                      Overland  ...               31.82
14                          Hale  ...               20.88
15               University Park  ...               27.27
16                     City Park  ...               32.20
17                 Union Station  ...               34.96
18                       Mar Lee  ...               33.33
19                   Harvey Park  ...               32.14
20                        Barnum  ...               30.30
21                      Rosedale  ...               35.00
22              Virginia Village  ...               34.00
23                Cory - Merrill  ...               38.10
24                Elyria Swansea  ...               24.00
25      Washington Virginia Vale  ...               16.22
26               South Park Hill  ...               19.15
27                         Regis  ...               39.02
28                 West Highland  ...               31.29
29                    Villa Park  ...               25.58
30           Northeast Park Hill  ...               32.73
31                 Congress Park  ...               28.13
32                   West Colfax  ...               26.67
33          Washington Park West  ...               22.06
34                   East Colfax  ...               30.61
35                  Capitol Hill  ...               35.04
36                      Berkeley  ...               20.23
37                    Globeville  ...               25.00
38                       Skyland  ...               21.28
39                      Westwood  ...               25.93
40               Washington Park  ...               30.00
41                 Cheesman Park  ...               18.48
42                         Baker  ...               25.00
43                      Whittier  ...               18.52
44                City Park West  ...               24.56
45                  Chaffee Park  ...               28.57
46                          Cole  ...               31.43
47                    University  ...               21.21
48                Jefferson Park  ...               19.54
49                   Five Points  ...               26.37
50               North Park Hill  ...               18.03
51                     Sunnyside  ...               21.37
52                    Sloan Lake  ...               20.43
53                       Clayton  ...               21.28
54                  Lincoln Park  ...               23.91
55                      Highland  ...               18.12
56                         Speer  ...               19.85
57                    Platt Park  ...               14.52
58                     Ruby Hill  ...               21.74

[59 rows x 6 columns]

In [73]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- For each stay policy and bedroom count, what percentage of listings have estimated_occupancy_l365d = 0?

stay_policy_bedrooms_occupancy AS (
	SELECT 
		stay_policy,
		bedrooms,
		COUNT(*) AS listings,
		SUM(CASE WHEN estimated_occupancy_l365d = 0 THEN 1 ELSE 0 END) AS zero_occupancy_listings,
		MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
		ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy
	FROM cleaned_listings
	WHERE stay_policy IS NOT NULL AND room_type = 'Entire home/apt' AND bedrooms BETWEEN 1 AND 3 AND stay_policy IN ('Short stay', 'Monthly stay')
	GROUP BY stay_policy, bedrooms
)

SELECT 
	stay_policy,
	bedrooms,
	listings,
	zero_occupancy_listings,
	ROUND(zero_occupancy_listings * 100.0 / listings, 2) AS pct_zero_occupancy
FROM stay_policy_bedrooms_occupancy
ORDER BY stay_policy, bedrooms;

    stay_policy  bedrooms  ...  zero_occupancy_listings  pct_zero_occupancy
0  Monthly stay         1  ...                    342.0               40.91
1  Monthly stay         2  ...                    353.0               50.72
2  Monthly stay         3  ...                    143.0               53.56
3    Short stay         1  ...                     24.0                3.17
4    Short stay         2  ...                     34.0                5.49
5    Short stay         3  ...                     21.0                5.82

[6 rows x 5 columns]

In [68]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does estimated occupancy differ across the major types of Denver Airbnb listings?

SELECT 
	bedrooms,
	COUNT(*) AS listings,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy
FROM cleaned_listings
WHERE room_type = 'Entire home/apt' AND bedrooms BETWEEN 1 AND 3
GROUP BY bedrooms
ORDER BY avg_estimated_occupancy DESC;

   bedrooms  listings  median_estimated_occupancy  avg_estimated_occupancy
0         1      1648                       116.0                   118.53
1         2      1352                        77.0                   104.02
2         3       638                        60.0                    94.24

In [66]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does estimated occupancy differ across the major types of Denver Airbnb listings?

SELECT 
	room_type,
	COUNT(*) AS listings,
	MEDIAN(estimated_occupancy_l365d) AS median_estimated_occupancy,
	ROUND(AVG(estimated_occupancy_l365d), 2) AS avg_estimated_occupancy
FROM cleaned_listings
GROUP BY room_type
ORDER BY avg_estimated_occupancy;

         room_type  ...  avg_estimated_occupancy
0       Hotel room  ...                    64.30
1      Shared room  ...                    73.71
2     Private room  ...                    81.04
3  Entire home/apt  ...                   107.90

[4 rows x 4 columns]

## Are amenity-rich listings associated with higher prices, and are there particular amenities associated with price premiums?

In [54]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Are amenity-rich listings associated with higher prices, and are there particular amenities associated with price premiums?

amenity_unnest AS (
    SELECT
        id,
        UNNEST(
            FROM_JSON(amenities, '["VARCHAR"]')
        ) AS amenity
    FROM cleaned_listings
),

has_amenity AS (
	SELECT 
		id,
		MAX(CASE 
			WHEN LOWER(amenity) LIKE '%pool%' AND LOWER(amenity) NOT LIKE '%pool table%' AND LOWER(amenity) NOT LIKE '%pool view%' AND LOWER(amenity) NOT LIKE '%whirlpool%' THEN 1
			ELSE 0
		END) AS has_pool
	FROM amenity_unnest
	GROUP BY id
),

has_amenity_pivot AS (
SELECT 
	l.bedrooms,
	SUM(CASE WHEN a.has_pool = 1 THEN 1 ELSE 0 END) AS pool_listings,
	MEDIAN(CASE WHEN a.has_pool = 1 THEN l.cleaned_price END) AS pool_median_price,
	SUM(CASE WHEN a.has_pool = 0 THEN 1 ELSE 0 END) AS no_pool_listings,
	MEDIAN(CASE WHEN a.has_pool = 0 THEN l.cleaned_price END) AS no_pool_median_price
FROM cleaned_listings AS l
INNER JOIN has_amenity AS a
	ON l.id = a.id
WHERE l.bedrooms <= 3 AND l.room_type = 'Entire home/apt' AND l.cleaned_price IS NOT NULL
GROUP BY l.bedrooms
)

SELECT *,
	ROUND((pool_median_price - no_pool_median_price) * 100.0 / no_pool_median_price, 2) AS pct_pool_premium
FROM has_amenity_pivot
ORDER BY bedrooms;

   bedrooms  pool_listings  ...  no_pool_median_price  pct_pool_premium
0         1          203.0  ...                145.15            -16.10
1         2          108.0  ...                198.00            -23.30
2         3           16.0  ...                325.85             -2.65

[3 rows x 6 columns]

In [36]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Are amenity-rich listings associated with higher prices, and are there particular amenities associated with price premiums?

amenity_comparison AS (
	SELECT 
		bedrooms,
		CASE 
			WHEN LOWER(amenities) LIKE '%hot tub%' THEN 'With hot tub'
			ELSE 'Without hot tub'
		END AS has_amenity,
		COUNT(*) AS listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings 
	WHERE cleaned_price IS NOT NULL AND room_type = 'Entire home/apt' AND bedrooms <= 3
	GROUP BY bedrooms, has_amenity
),

amenity_comparison_pivot AS (
	SELECT 
		bedrooms,
		MAX(CASE WHEN has_amenity = 'With hot tub' THEN listings END) AS hot_tub_listings,
		MAX(CASE WHEN has_amenity = 'Without hot tub' THEN listings END) AS no_hot_tub_listings,
		MAX(CASE WHEN has_amenity = 'With hot tub' THEN median_price END) AS hot_tub_median,
		MAX(CASE WHEN has_amenity = 'Without hot tub' THEN median_price END) AS no_hot_tub_median
	FROM amenity_comparison
	GROUP BY bedrooms
)

SELECT *,
	hot_tub_median - no_hot_tub_median AS price_difference,
	ROUND((hot_tub_median - no_hot_tub_median) * 100.0 / no_hot_tub_median, 2) AS pct_premium
FROM amenity_comparison_pivot
ORDER BY bedrooms;

   bedrooms  hot_tub_listings  ...  price_difference  pct_premium
0         1               150  ...             22.36        16.33
1         2               103  ...             91.93        48.88
2         3                59  ...            152.00        49.19

[3 rows x 7 columns]

In [46]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Are amenity-rich listings associated with higher prices, and are there particular amenities associated with price premiums?

amenity_unnest AS (
    SELECT
        id,
        UNNEST(
            FROM_JSON(amenities, '["VARCHAR"]')
        ) AS amenity
    FROM cleaned_listings
)

SELECT
    amenity,
    COUNT(DISTINCT id) AS listings
FROM amenity_unnest
WHERE LOWER(amenity) LIKE '%pool%'
GROUP BY amenity
ORDER BY listings DESC;

                                              amenity  listings
0                                                Pool       248
1                                          Pool table       239
2                                         Shared pool        58
3                              Whirlpool refrigerator        40
4   Shared outdoor pool - open specific hours, roo...        24
..                                                ...       ...
92  Private outdoor pool - available all year, ope...         1
93  Shared pool - available all year, open specifi...         1
94  Shared outdoor pool - available all year, rooftop         1
95                  Shared pool - open specific hours         1
96  Whirlpool Gold Chef Gas 5 Burner Rapid Preheat...         1

[97 rows x 2 columns]

In [33]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Are amenity-rich listings associated with higher prices, and are there particular amenities associated with price premiums?

amenity_unnest AS (
	SELECT
	    id,
		cleaned_price,
	    UNNEST(
	        FROM_JSON(amenities, '["VARCHAR"]')
	    ) AS amenity
	FROM cleaned_listings
)
	
SELECT 
	amenity,
	COUNT(DISTINCT id) AS listings,
	MEDIAN(cleaned_price) AS median_price
FROM amenity_unnest
WHERE amenity IS NOT NULL AND cleaned_price IS NOT NULL
GROUP BY amenity
HAVING COUNT(DISTINCT id) >= 10
ORDER BY median_price DESC;

                                               amenity  listings  median_price
0                              Private outdoor kitchen        16        522.95
1                          Stainless steel double oven        20        493.88
2    Private hot tub - available all year, open spe...        16        491.85
3                                  Children's playroom        51        485.00
4                                   Sonos sound system        26        482.25
..                                                 ...       ...           ...
337                                Dryer – In building        25         92.77
338                               Lock on bedroom door       250         88.75
339  Shared outdoor pool - open specific hours, roo...        20         83.06
340  Coffee maker: drip coffee maker, espresso mach...        20         69.00
341                         Shared BBQ grill: charcoal        14         67.63

[342 rows x 3 columns]

In [31]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Are amenity-rich listings associated with higher prices, and are there particular amenities associated with price premiums?

SELECT 
	bedrooms,
	CASE 
		WHEN amenity_count <= 10 THEN '10 or Less Amenities'
		WHEN amenity_count <= 20 THEN '11-20 Amenities'
		WHEN amenity_count <= 30 THEN '21-30 Amenities'
		WHEN amenity_count <= 40 THEN '31-40 Amenities' 
		WHEN amenity_count <= 50 THEN '41-50 Amenities'
		WHEN amenity_count <= 60 THEN '51-60 Amenities'
		WHEN amenity_count <= 70 THEN '61-70 Amenities'
		WHEN amenity_count <= 80 THEN '71-80 Amenities'
		ELSE 'Over 80 Amenities'
	END AS amenity_count_category,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price
FROM cleaned_listings 
WHERE cleaned_price IS NOT NULL AND room_type = 'Entire home/apt' AND bedrooms <= 3
GROUP BY bedrooms, amenity_count_category
HAVING COUNT(*) >= 20
ORDER BY bedrooms, amenity_count_category;

    bedrooms amenity_count_category  listings  median_price
0          1   10 or Less Amenities        24         86.71
1          1        11-20 Amenities       101        119.82
2          1        21-30 Amenities       192        118.72
3          1        31-40 Amenities       314        147.00
4          1        41-50 Amenities       406        148.75
5          1        51-60 Amenities       286        155.05
6          1        61-70 Amenities        92        153.61
7          2        11-20 Amenities        97        128.33
8          2        21-30 Amenities        73        174.48
9          2        31-40 Amenities       171        149.89
10         2        41-50 Amenities       320        189.66
11         2        51-60 Amenities       309        231.37
12         2        61-70 Amenities       129        281.00
13         3        11-20 Amenities        35        191.30
14         3        21-30 Amenities        22        193.80
15         3        31-40 Amenities        64        290.80
16         3        41-50 Amenities       131        275.97
17         3        51-60 Amenities       151        361.50
18         3        61-70 Amenities       103        394.32
19         3        71-80 Amenities        30        491.95

## Within each room type, how does median nightly price differ across stay policies? | Within comparable bedroom counts, how does median nightly price differ between short-stay and monthly-stay listings?

In [20]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Within (Entire home/apt) comparable bedroom counts, how does median nightly price differ between short-stay and monthly-stay listings?

bedrooms_stay_policy AS (
	SELECT 
		bedrooms,
		stay_policy,
		COUNT(*) AS listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings
	WHERE bedrooms <= 3 AND room_type = 'Entire home/apt' AND stay_policy IN ('Short stay', 'Monthly stay') AND cleaned_price IS NOT NULL 
	GROUP BY bedrooms, stay_policy
),

bedrooms_stay_policy_pivot AS (
SELECT 
	bedrooms,
	MAX(CASE WHEN stay_policy = 'Short stay' THEN listings END) AS short_listings,
	MAX(CASE WHEN stay_policy = 'Monthly stay' THEN listings END) AS monthly_listings,
	MAX(CASE WHEN stay_policy = 'Short stay' THEN median_price END) AS short_median,
	MAX(CASE WHEN stay_policy = 'Monthly stay' THEN median_price END) AS monthly_median
FROM bedrooms_stay_policy
GROUP BY bedrooms
)

SELECT *,
	short_median - monthly_median AS median_difference,
	ROUND((short_median - monthly_median) * 100.0 / short_median, 2) AS pct_monthly_discount
FROM bedrooms_stay_policy_pivot
ORDER BY bedrooms;

   bedrooms  short_listings  ...  median_difference  pct_monthly_discount
0         1             706  ...             111.76                 53.80
1         2             572  ...             169.38                 57.86
2         3             338  ...             254.64                 58.74

[3 rows x 7 columns]

In [10]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Within each room type, how does median nightly price differ across stay policies?

SELECT 
	room_type,
	stay_policy,
	COUNT(*) AS listings,
	MEDIAN(cleaned_price) AS median_price
FROM cleaned_listings
WHERE stay_policy IS NOT NULL AND cleaned_price IS NOT NULL
GROUP BY room_type, stay_policy
ORDER BY room_type, median_price DESC;

          room_type    stay_policy  listings  median_price
0   Entire home/apt     Short stay      1949        285.50
1   Entire home/apt    Medium Stay        18        168.83
2   Entire home/apt   Monthly stay      1598        115.33
3   Entire home/apt  Extended stay        63         38.82
4        Hotel room     Short stay        19        383.00
5        Hotel room   Monthly stay         2         88.25
6      Private room    Medium Stay        10        570.71
7      Private room     Short stay       302        137.00
8      Private room   Monthly stay       235         54.30
9      Private room  Extended stay         7         15.88
10      Shared room     Short stay        21         47.00
11      Shared room   Monthly stay        26         20.48

## How does minimum-night strategy relate to nightly price?

In [9]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How does minimum-night strategy relate to nightly price?

SELECT 
	stay_policy,
	COUNT(*) AS listings,
	ROUND(AVG(minimum_nights), 2) AS avg_minimum_nights,
	ROUND(MEDIAN(cleaned_price), 2) AS median_price
FROM cleaned_listings
WHERE minimum_nights IS NOT NULL AND cleaned_price IS NOT NULL
GROUP BY stay_policy
ORDER BY median_price DESC;

     stay_policy  listings  avg_minimum_nights  median_price
0     Short stay      2291                1.57        261.50
1    Medium Stay        28               10.79        178.40
2   Monthly stay      1861               29.52        108.51
3  Extended stay        70               97.97         37.59

## Among Entire home/apt listings with the same bedroom count, how does median price vary by host scale? | Within the same neighborhood and bedroom count, do single-listing hosts generally have higher median prices than multi-listing hosts?

In [10]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- How does host scale relate to nightly price? Do large/professional operators charge systematically different prices than single-listing and smaller hosts?
-- Among Entire home/apt listings, how does median nightly price vary by host scale?
-- Among Entire home/apt listings with the same bedroom count, how does median price vary by host scale?
-- Within the same neighborhood and bedroom count, do single-listing hosts generally have higher median prices than multi-listing hosts?
-- After controlling for neighborhood and bedroom count, do Single-listing hosts price differently from Large/professional operators?

host_scale_prices AS (
	SELECT
		neighbourhood_cleansed,
		bedrooms,
		host_scale,
		COUNT(DISTINCT host_id) AS distinct_hosts,
		COUNT(*) AS listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings
	WHERE cleaned_price IS NOT NULL 
		AND room_type = 'Entire home/apt'
		AND bedrooms IS NOT NULL AND bedrooms <= 3 
		AND host_scale IN ('Single-listing host', 'Large/professional operator')
	GROUP BY neighbourhood_cleansed, bedrooms, host_scale
),

host_scale_comparison AS (
	SELECT 
		neighbourhood_cleansed,
		bedrooms,
		SUM(CASE WHEN host_scale = 'Single-listing host' THEN listings ELSE 0 END) AS single_listings,
		SUM(CASE WHEN host_scale = 'Large/professional operator' THEN listings ELSE 0 END) AS professional_listings
	FROM host_scale_prices
	GROUP BY neighbourhood_cleansed, bedrooms
),

thresholds AS (
	SELECT *
	FROM (VALUES
		(1),
		(2),
		(3),
		(5),
		(10),
		(15)
	) AS t(minimum_priced_listings)
),

total_listings AS (
	SELECT 
		COUNT(*) AS total_listings
	FROM cleaned_listings
	WHERE cleaned_price IS NOT NULL 
		AND room_type = 'Entire home/apt'
		AND bedrooms IS NOT NULL AND bedrooms <= 3 
		AND host_scale IN ('Single-listing host', 'Large/professional operator')
)

SELECT 
	t.minimum_priced_listings,
	COUNT(*) AS groups_retained,
	SUM(h.single_listings + h.professional_listings) AS listings_retained,
	ROUND(SUM(h.single_listings + h.professional_listings) * 100.0 / l.total_listings, 2) AS percent_of_listings_retained
FROM host_scale_comparison AS h
INNER JOIN thresholds AS t 
	ON h.single_listings >= t.minimum_priced_listings
	AND h.professional_listings >= t.minimum_priced_listings
CROSS JOIN total_listings AS l
GROUP BY t.minimum_priced_listings, l.total_listings, 
ORDER BY t.minimum_priced_listings;

   minimum_priced_listings  ...  percent_of_listings_retained
0                        1  ...                         76.98
1                        2  ...                         63.53
2                        3  ...                         52.94
3                        5  ...                         36.77
4                       10  ...                         25.02
5                       15  ...                         12.81

[6 rows x 4 columns]

In [18]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- How does host scale relate to nightly price? Do large/professional operators charge systematically different prices than single-listing and smaller hosts?
-- Among Entire home/apt listings, how does median nightly price vary by host scale?
-- Among Entire home/apt listings with the same bedroom count, how does median price vary by host scale?
-- Within the same neighborhood and bedroom count, do single-listing hosts generally have higher median prices than multi-listing hosts?

host_scale_prices AS (
	SELECT
		neighbourhood_cleansed,
		bedrooms,
		host_scale,
		COUNT(DISTINCT host_id) AS distinct_hosts,
		COUNT(*) AS listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings
	WHERE cleaned_price IS NOT NULL 
		AND room_type = 'Entire home/apt'
		AND bedrooms IS NOT NULL AND bedrooms <= 3 
		AND host_scale IN ('Single-listing host', 'Large/professional operator')
	GROUP BY neighbourhood_cleansed, bedrooms, host_scale
),

host_scale_comparison AS (
	SELECT 
		neighbourhood_cleansed,
		bedrooms,
		SUM(CASE WHEN host_scale = 'Single-listing host' THEN listings ELSE 0 END) AS single_listings,
		SUM(CASE WHEN host_scale = 'Large/professional operator' THEN listings ELSE 0 END) AS professional_listings,
		MAX(CASE WHEN host_scale = 'Single-listing host' THEN median_price END) AS single_median,
		MAX(CASE WHEN host_scale = 'Large/professional operator' THEN median_price END) AS professional_median
	FROM host_scale_prices
	GROUP BY neighbourhood_cleansed, bedrooms
),

host_scale_medians AS (
	SELECT 
		neighbourhood_cleansed,
		bedrooms,
		single_median,	
		professional_median,
		single_median - professional_median AS difference,
		ROUND((single_median - professional_median) * 100.0 / professional_median, 2) AS pct_difference
	FROM host_scale_comparison
	WHERE single_listings >= 3 AND professional_listings >= 3
),

host_comparison_result AS (
	SELECT 
		CASE 
			WHEN difference > 0 THEN 'Single-listing host more expensive'
			WHEN difference < 0 THEN 'Professional operator more expensive'
			WHEN difference = 0 THEN 'Same median price'
		END AS comparison_result,
		COUNT(*) AS groups,
		ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS pct_of_groups
	FROM host_scale_medians
	GROUP BY comparison_result
)

SELECT 
	MEDIAN(pct_difference) AS median_pct_difference_across_all_groups,
	MEDIAN(CASE WHEN difference > 0 THEN pct_difference END) AS median_pct_difference_when_single_more_expensive,
	MEDIAN(ABS(pct_difference)) AS median_absolute_pct_difference
FROM host_scale_medians;

   median_pct_difference_across_all_groups  ...  median_absolute_pct_difference
0                                    28.46  ...                           35.63

[1 rows x 3 columns]

## How does host scale relate to nightly price? Do large/professional operators charge systematically different prices than single-listing and smaller hosts?

In [79]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- How does host scale relate to nightly price? Do large/professional operators charge systematically different prices than single-listing and smaller hosts?

host_scale_prices AS (
	SELECT
		host_scale,
		COUNT(DISTINCT host_id) AS distinct_hosts,
		COUNT(*) AS listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings
	WHERE cleaned_price IS NOT NULL 
	GROUP BY host_scale
),

overall_median AS (
	SELECT 
		MEDIAN(cleaned_price) AS overall_median
	FROM cleaned_listings
	WHERE cleaned_price IS NOT NULL 
)

SELECT *,
	ROUND((h.median_price - m.overall_median) * 100.0 / m.overall_median, 2) AS median_percent_change
FROM host_scale_prices AS h
CROSS JOIN overall_median AS m
ORDER BY listings DESC;

                    host_scale  ...  median_percent_change
0          Single-listing host  ...                   8.53
1     Small multi-listing host  ...                 -12.36
2  Large/professional operator  ...                 -14.42
3              Medium operator  ...                 -23.88

[4 rows x 6 columns]

## Within Entire home/apt listings, how does capacity/property size affect price? | Among similarly sized Entire homes/apartments, which Denver neighborhoods command higher or lower nightly prices? | For 1-, 2-, and 3-bedroom Entire home/apts, how far above or below the Denver-wide median for the same bedroom count is each qualifying neighborhood's median price?

In [76]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Among similarly sized Entire homes/apartments, which Denver neighborhoods command higher or lower nightly prices?
-- For 1-, 2-, and 3-bedroom Entire home/apts, how far above or below the Denver-wide median for the same bedroom count is each qualifying neighborhood's median price?

neighbourhood_bedroom_prices AS (
	SELECT 
		neighbourhood_cleansed,
		bedrooms,
		COUNT(*) AS priced_listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings
	WHERE room_type = 'Entire home/apt' AND cleaned_price IS NOT NULL AND bedrooms IS NOT NULL AND bedrooms <= 3
	GROUP BY neighbourhood_cleansed, bedrooms
	HAVING COUNT(*) >= 5
),

median_prices AS (
	SELECT 
		bedrooms,
		MEDIAN(cleaned_price) AS entirehomeapt_bedrooms_median_price
	FROM cleaned_listings
	WHERE room_type = 'Entire home/apt' AND cleaned_price IS NOT NULL AND bedrooms IS NOT NULL AND bedrooms <= 3
	GROUP BY bedrooms
),
	
neighbourhood_bedroom_prices_rank AS (
	SELECT n.*, 
		m.entirehomeapt_bedrooms_median_price,
		ROUND((n.median_price - m.entirehomeapt_bedrooms_median_price) * 100.0 / m.entirehomeapt_bedrooms_median_price, 2) AS median_percent_change,
		ROW_NUMBER() OVER (
			PARTITION BY n.bedrooms
			ORDER BY n.median_price DESC
		) AS bedroom_median_price_high_rank,
		ROW_NUMBER() OVER (
			PARTITION BY n.bedrooms
			ORDER BY n.median_price
		) AS bedroom_median_price_low_rank
	FROM neighbourhood_bedroom_prices AS n
	INNER JOIN median_prices AS m
		ON n.bedrooms = m.bedrooms
)

SELECT *,
	CASE 
		WHEN bedroom_median_price_high_rank <= 5 THEN 'Top 5 Premium'
		WHEN bedroom_median_price_low_rank <= 5 THEN 'Top 5 Discount'
		WHEN median_percent_change > 0 THEN 'Premium'
		WHEN median_percent_change < 0 THEN 'Discount'
	END AS price_position
FROM neighbourhood_bedroom_prices_rank 
WHERE bedroom_median_price_high_rank <= 5 OR bedroom_median_price_low_rank <= 5
ORDER BY bedrooms DESC, median_price DESC;

          neighbourhood_cleansed  ...  price_position
0                       Highland  ...   Top 5 Premium
1                 Jefferson Park  ...   Top 5 Premium
2                    Five Points  ...   Top 5 Premium
3           Washington Park West  ...   Top 5 Premium
4                          Speer  ...   Top 5 Premium
5   Gateway - Green Valley Ranch  ...  Top 5 Discount
6                North Park Hill  ...  Top 5 Discount
7                    Athmar Park  ...  Top 5 Discount
8       Washington Virginia Vale  ...  Top 5 Discount
9            Northeast Park Hill  ...  Top 5 Discount
10                Jefferson Park  ...   Top 5 Premium
11                 Union Station  ...   Top 5 Premium
12                  Cherry Creek  ...   Top 5 Premium
13               Washington Park  ...   Top 5 Premium
14                      Whittier  ...   Top 5 Premium
15                     City Park  ...  Top 5 Discount
16                 Hampden South  ...  Top 5 Discount
17                          Hale  ...  Top 5 Discount
18                      Westwood  ...  Top 5 Discount
19                           DIA  ...  Top 5 Discount
20                  Cherry Creek  ...   Top 5 Premium
21                  Civic Center  ...   Top 5 Premium
22                       Skyland  ...   Top 5 Premium
23                  Chaffee Park  ...   Top 5 Premium
24                    Platt Park  ...   Top 5 Premium
25                  Capitol Hill  ...  Top 5 Discount
26                        Barnum  ...  Top 5 Discount
27           Northeast Park Hill  ...  Top 5 Discount
28                    Fort Logan  ...  Top 5 Discount
29                   East Colfax  ...  Top 5 Discount

[30 rows x 9 columns]

In [58]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Among similarly sized Entire homes/apartments, which Denver neighborhoods command higher or lower nightly prices?

neighbourhood_bedroom_prices AS (
	SELECT 
		neighbourhood_cleansed,
		bedrooms,
		COUNT(*) AS priced_listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings
	WHERE room_type = 'Entire home/apt' AND cleaned_price IS NOT NULL AND bedrooms IS NOT NULL AND bedrooms <= 3
	GROUP BY neighbourhood_cleansed, bedrooms
	HAVING COUNT(*) >= 5
),

neighbourhood_bedroom_prices_rank AS (
	SELECT *,
		ROW_NUMBER() OVER (
			PARTITION BY bedrooms
			ORDER BY median_price DESC
		) AS bedroom_median_price_rank
	FROM neighbourhood_bedroom_prices
)

SELECT *
FROM neighbourhood_bedroom_prices_rank 
WHERE bedroom_median_price_rank <= 5
ORDER BY bedrooms DESC, median_price DESC;

   neighbourhood_cleansed  bedrooms  ...  median_price  bedroom_median_price_rank
0                Highland         3  ...        567.49                          1
1          Jefferson Park         3  ...        527.00                          2
2             Five Points         3  ...        474.82                          3
3    Washington Park West         3  ...        446.83                          4
4                   Speer         3  ...        426.47                          5
5          Jefferson Park         2  ...        340.91                          1
6           Union Station         2  ...        335.00                          2
7            Cherry Creek         2  ...        292.50                          3
8         Washington Park         2  ...        290.32                          4
9                Whittier         2  ...        287.00                          5
10           Cherry Creek         1  ...        277.00                          1
11           Civic Center         1  ...        230.50                          2
12                Skyland         1  ...        226.81                          3
13           Chaffee Park         1  ...        225.50                          4
14             Platt Park         1  ...        213.25                          5

[15 rows x 5 columns]

In [55]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Among similarly sized Entire homes/apartments, which Denver neighborhoods command higher or lower nightly prices?

neighbourhood_bedroom_prices AS (
	SELECT 
		neighbourhood_cleansed,
		bedrooms,
		COUNT(*) AS priced_listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings
	WHERE room_type = 'Entire home/apt' AND cleaned_price IS NOT NULL AND bedrooms IS NOT NULL AND bedrooms <= 3
	GROUP BY neighbourhood_cleansed, bedrooms
),

threshold AS (
	SELECT *
	FROM (VALUES
		(5), (10), (15), (20), (25), (30), (50)
	) AS t(minimum_priced_listings)
),

neighbourhood_bedroom_prices_threshold AS (
	SELECT 
		t.minimum_priced_listings,
		COUNT(DISTINCT neighbourhood_cleansed) AS retained_neighbourhoods,
		SUM(priced_listings) AS retained_listings
	FROM neighbourhood_bedroom_prices AS n
	INNER JOIN threshold AS t ON n.priced_listings >= t.minimum_priced_listings
	GROUP BY t.minimum_priced_listings
),

total_listings AS (
	SELECT 
		COUNT(*) AS total_listings
	FROM cleaned_listings
	WHERE room_type = 'Entire home/apt' AND cleaned_price IS NOT NULL AND bedrooms IS NOT NULL AND bedrooms <= 3
)

SELECT n.*,
	ROUND(n.retained_listings * 100.0 / t.total_listings, 2) AS percent_of_listings
FROM neighbourhood_bedroom_prices_threshold AS n
CROSS JOIN total_listings AS t
ORDER BY n.minimum_priced_listings;

   minimum_priced_listings  ...  percent_of_listings
0                        5  ...                94.20
1                       10  ...                83.03
2                       15  ...                71.01
3                       20  ...                64.41
4                       25  ...                55.33
5                       30  ...                48.37
6                       50  ...                29.50

[7 rows x 4 columns]

In [52]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among priced Entire home/apt listings, how many have a NULL bedroom count, and what percentage of those listings does that represent?

SELECT
    SUM(CASE WHEN bedrooms IS NULL THEN 1 ELSE 0 END) AS null_bedroom_count,
    COUNT(*) AS entire_home_apt_listings,
    ROUND(
        SUM(CASE WHEN bedrooms IS NULL THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS null_bedroom_pct
FROM cleaned_listings
WHERE room_type = 'Entire home/apt'
  AND cleaned_price IS NOT NULL;

   null_bedroom_count  entire_home_apt_listings  null_bedroom_pct
0               164.0                      3629              4.52

In [48]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Within Entire home/apt listings, how does capacity/property size affect price?

SELECT 
	bedrooms,
	COUNT(*) AS priced_listings,
	MEDIAN(cleaned_price) AS median_price
FROM cleaned_listings
WHERE room_type = 'Entire home/apt' AND bedrooms IS NOT NULL AND cleaned_price IS NOT NULL 
GROUP BY bedrooms
ORDER BY median_price DESC;

    bedrooms  priced_listings  median_price
0         10                1       1814.00
1          8                3       1116.52
2          9                2        916.43
3          6               32        719.25
4          7                6        603.33
5          5               90        564.64
6          4              225        495.33
7          3              544        325.85
8          2             1133        193.00
9         15                1        164.11
10         1             1428        140.06

In [44]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Within Entire home/apt listings, how does capacity/property size affect price?

SELECT 
	accommodates,
	COUNT(*) AS priced_listings,
	MEDIAN(cleaned_price) AS median_price
FROM cleaned_listings
WHERE room_type = 'Entire home/apt' AND cleaned_price IS NOT NULL 
GROUP BY accommodates
ORDER BY median_price DESC;

    accommodates  priced_listings  median_price
0             13                6        866.75
1             14               24        790.00
2             16               33        634.00
3             12               62        610.64
4             15                5        547.10
5             11               13        532.93
6             10              112        531.19
7              9               33        466.52
8              8              206        368.94
9              7               65        325.70
10             6              459        292.75
11             5              211        249.00
12             4             1009        184.85
13             3              302        158.78
14             2             1053        118.14
15             1               36         77.36

## Do neighborhood price differences persist when we compare the same room type? | Among neighborhoods with sufficient Entire home/apt inventory, which neighborhoods have the highest and lowest median nightly prices for Entire homes/apartments?

In [38]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Among neighborhoods with sufficient Entire home/apt inventory, which neighborhoods have the highest and lowest median nightly prices for Entire homes/apartments?

neighbourhood_pricing_entirehomeapt AS (
	SELECT 
		neighbourhood_cleansed,
		COUNT(*) AS priced_listings,
		MEDIAN(cleaned_price) AS median_price
	FROM cleaned_listings 
	WHERE cleaned_price IS NOT NULL AND room_type = 'Entire home/apt'
	GROUP BY neighbourhood_cleansed
),

threshold AS (
	SELECT *
	FROM (VALUES
		(5), (10), (15), (20), (25), (30), (50)
	) AS t(minimum_priced_listings)
),

neighbourhood_pricing_entirehomeapt_thresholds AS (
	SELECT 
		t.minimum_priced_listings,
		COUNT(neighbourhood_cleansed) AS neighbourhoods_retained,
		SUM(priced_listings) AS priced_listings_retained
	FROM neighbourhood_pricing_entirehomeapt AS n
	INNER JOIN threshold AS t ON n.priced_listings >= t.minimum_priced_listings
	GROUP BY t.minimum_priced_listings
),

total_entirehomeapt_listings AS (
	SELECT 
		COUNT(*) AS total_entirehomeapt_listings
	FROM cleaned_listings 
	WHERE cleaned_price IS NOT NULL AND room_type = 'Entire home/apt'
)

SELECT n.*,
	ROUND(n.priced_listings_retained * 100.0 / t.total_entirehomeapt_listings, 2) AS percent_of_listings_retained
FROM neighbourhood_pricing_entirehomeapt_thresholds AS n
CROSS JOIN total_entirehomeapt_listings AS t
ORDER BY n.minimum_priced_listings;

   minimum_priced_listings  ...  percent_of_listings_retained
0                        5  ...                         99.86
1                       10  ...                         97.91
2                       15  ...                         95.10
3                       20  ...                         91.93
4                       25  ...                         88.21
5                       30  ...                         86.06
6                       50  ...                         71.76

[7 rows x 4 columns]

In [43]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Among neighborhoods with sufficient Entire home/apt inventory, which neighborhoods have the highest and lowest median nightly prices for Entire homes/apartments?

SELECT 
	neighbourhood_cleansed,
	COUNT(*) AS priced_listings,
	MEDIAN(cleaned_price) AS median_price
FROM cleaned_listings 
WHERE cleaned_price IS NOT NULL AND room_type = 'Entire home/apt'
GROUP BY neighbourhood_cleansed
HAVING COUNT(*) >= 15
ORDER BY median_price;

          neighbourhood_cleansed  priced_listings  median_price
0                      City Park               52        100.13
1                   Capitol Hill               98        102.81
2                            CBD              124        109.75
3                       Overland               22        114.81
4            Northeast Park Hill               37        121.66
5                    East Colfax               35        121.90
6                  Hampden South               21        124.48
7                          Speer              122        135.43
8                           Hale               73        136.52
9                  Cheesman Park               80        142.39
10            North Capitol Hill               36        142.61
11                         Baker               83        146.63
12                      Westwood               25        147.21
13                        Barnum               28        158.16
14                City Park West               82        159.40
15                 Congress Park               74        172.08
16                      Rosedale               15        172.42
17                    University               24        173.33
18      Washington Virginia Vale               25        175.36
19                   Athmar Park               46        178.37
20                     Montclair               23        185.79
21                  Lincoln Park               67        187.00
22                       Clayton               41        188.00
23                    Villa Park               32        192.50
24               North Park Hill               43        193.00
25               Washington Park               31        193.35
26                 Union Station              172        194.90
27                    Platt Park               47        202.50
28                 West Highland              103        205.00
29                         Regis               30        207.25
30  Gateway - Green Valley Ranch               95        209.07
31                    Sloan Lake               75        210.38
32                          Cole               70        216.00
33                   West Colfax              147        217.00
34                     Ruby Hill               18        217.93
35                    Globeville               15        218.00
36              Virginia Village               38        219.54
37               South Park Hill               32        219.72
38                Cory - Merrill               16        220.55
39                     Stapleton               63        220.83
40                   Five Points              297        220.91
41                      Berkeley              128        221.50
42                  Chaffee Park               24        226.50
43                     Sunnyside              103        228.00
44          Washington Park West               59        230.62
45                  Civic Center               39        234.00
46                      Valverde               16        234.58
47                      Whittier               72        239.00
48              University Hills               21        246.75
49                      Highland              255        252.20
50                       Skyland               32        258.23
51                       Hampden               17        266.76
52                Jefferson Park               60        311.66
53                  Cherry Creek               50        315.94
54               University Park               18        369.41

## Which Denver neighborhoods are the most and least expensive based on median nightly price? | How many neighborhoods and priced listings would remain if we required at least 5, 10, 20, 30, and 50 priced listings per neighborhood?

In [25]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Which Denver neighborhoods are the most and least expensive based on median nightly price?

neighbourhood_pricing AS (
	SELECT
		neighbourhood_cleansed,
		COUNT(*) AS priced_listings,
		MEDIAN(cleaned_price) AS median_price,
		ROUND(AVG(cleaned_price), 2) AS avg_price,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1_price,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3_price
	FROM cleaned_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY neighbourhood_cleansed
),
	
-- How many neighborhoods and priced listings would remain if we required at least 5, 10, 20, 30, and 50 priced listings per neighborhood?

thresholds AS (
	SELECT *
	FROM (VALUES
		(5),
		(10),
		(20),
		(30),
		(50)
	) AS t(minimum_priced_listings)
),

neighbourhood_pricing_thresholds AS (
	SELECT 
		t.minimum_priced_listings,
		COUNT(n.neighbourhood_cleansed) AS neighbourhoods_retained,
		SUM(n.priced_listings) AS priced_listings_retained
	FROM neighbourhood_pricing AS n
	INNER JOIN thresholds as t 
		ON n.priced_listings >= t.minimum_priced_listings
	GROUP BY t.minimum_priced_listings
),

total_priced_listings AS (
	SELECT 
		COUNT(*) AS total_priced_listings
	FROM cleaned_listings
	WHERE cleaned_price IS NOT NULL
)

SELECT n.*,
	ROUND(n.priced_listings_retained * 100.0 / t.total_priced_listings, 2) AS percent_of_priced_listings_retained
FROM neighbourhood_pricing_thresholds AS n
CROSS JOIN total_priced_listings AS t
ORDER BY n.minimum_priced_listings;

   minimum_priced_listings  ...  percent_of_priced_listings_retained
0                        5  ...                                99.91
1                       10  ...                                98.80
2                       20  ...                                93.67
3                       30  ...                                86.66
4                       50  ...                                74.66

[5 rows x 4 columns]

In [31]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- Which Denver neighborhoods are the most and least expensive based on median nightly price?

SELECT
	neighbourhood_cleansed,
	COUNT(*) AS priced_listings,
	MEDIAN(cleaned_price) AS median_price,
	ROUND(AVG(cleaned_price), 2) AS avg_price,
	ROUND(AVG(cleaned_price) - MEDIAN(cleaned_price), 2) AS avg_median_difference,
	QUANTILE_CONT(cleaned_price, 0.25) AS q1_price,
	QUANTILE_CONT(cleaned_price, 0.75) AS q3_price,
	QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
FROM cleaned_listings
WHERE cleaned_price IS NOT NULL
GROUP BY neighbourhood_cleansed
HAVING COUNT(*) >= 20
ORDER BY median_price DESC;

          neighbourhood_cleansed  priced_listings  ...  q3_price     iqr
0                        Hampden               24  ...    572.64  472.87
1                   Cherry Creek               53  ...    482.50  298.00
2                 Jefferson Park               71  ...    444.27  298.19
3                       Highland              266  ...    416.03  283.14
4                       Berkeley              151  ...    350.18  195.67
5               University Hills               22  ...    437.75  322.70
6                        Skyland               37  ...    347.00  189.00
7                   Civic Center               40  ...    261.29   65.78
8                      Sunnyside              105  ...    350.25  205.25
9                   Chaffee Park               26  ...    324.02  158.79
10                    Sloan Lake               81  ...    311.54  180.17
11          Washington Park West               63  ...    375.33  256.29
12                      Whittier               89  ...    291.00  164.00
13                         Regis               33  ...    283.97  154.84
14                     Stapleton               79  ...    297.04  182.73
15                          Cole               96  ...    287.25  152.85
16                    Platt Park               51  ...    262.00  115.32
17                   West Colfax              158  ...    385.11  260.91
18                   Five Points              353  ...    360.00  249.48
19              Virginia Village               46  ...    300.12  172.79
20               Washington Park               33  ...    326.15  186.15
21                    Villa Park               34  ...    323.91  195.54
22               South Park Hill               42  ...    339.67  231.67
23                 Union Station              200  ...    345.25  221.41
24                  Lincoln Park               73  ...    326.00  208.16
25                       Clayton               43  ...    264.87  137.00
26               North Park Hill               51  ...    279.11  139.10
27                 West Highland              118  ...    276.77  168.09
28      Washington Virginia Vale               28  ...    217.87  101.27
29                     Montclair               24  ...    273.07  148.75
30                   Athmar Park               51  ...    259.56  133.76
31                 Congress Park               79  ...    227.83  134.77
32                        Barnum               29  ...    261.00  171.28
33                    University               29  ...    221.51  118.51
34                City Park West              103  ...    262.86  177.01
35                      Westwood               25  ...    235.98  156.74
36                         Baker               94  ...    238.81  135.65
37                         Speer              127  ...    219.74  125.02
38            North Capitol Hill               39  ...    291.60  195.64
39                          Hale               77  ...    186.58  110.67
40                 Cheesman Park               87  ...    191.00  103.90
41                           DIA               22  ...    187.37  113.57
42                           CBD              143  ...    185.61   94.00
43                   East Colfax               43  ...    236.50  146.25
44                 Hampden South               30  ...    257.70  175.96
45           Northeast Park Hill               49  ...    164.41   84.61
46                Elyria Swansea               22  ...    191.50  147.46
47  Gateway - Green Valley Ranch              180  ...    220.90  158.18
48                   Harvey Park               23  ...    217.63  163.03
49                  Capitol Hill              122  ...    198.00  118.28
50                     City Park               53  ...    143.75   56.26
51                      Overland               41  ...    125.00  107.00
52                     Goldsmith               24  ...    124.55   78.51

[53 rows x 8 columns]

## How do nightly prices differ by room type?

In [12]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How sensitive are room-type price estimates to high-price outliers?

SELECT 
	room_type,
	ROUND(AVG(cleaned_price), 2) AS full_data_mean,
	ROUND(AVG(CASE WHEN price_status != 'High price outlier' THEN cleaned_price END), 2) AS typical_range_mean,
	ROUND(AVG(cleaned_price) - AVG(CASE WHEN price_status != 'High price outlier' THEN cleaned_price END), 2) AS change_in_mean,
	ROUND(
		(
		AVG(cleaned_price) 
		- AVG(CASE WHEN price_status != 'High price outlier' THEN cleaned_price END) 
		)
		* 100.0 / AVG(cleaned_price), 
		2) AS pct_change_in_mean,
	MEDIAN(cleaned_price) AS full_data_median,
	MEDIAN(CASE WHEN price_status != 'High price outlier' THEN cleaned_price END) AS typical_range_median
FROM cleaned_listings
WHERE cleaned_price IS NOT NULL 
GROUP BY room_type
ORDER BY room_type;

         room_type  full_data_mean  ...  full_data_median  typical_range_median
0  Entire home/apt          297.35  ...            190.59                180.62
1       Hotel room          370.83  ...            378.00                378.00
2     Private room          152.98  ...            106.00                102.00
3      Shared room           39.03  ...             35.00                 35.00

[4 rows x 7 columns]

In [7]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How do nightly prices differ by room type?

SELECT 
	room_type,
	COUNT(*) AS priced_listings,
	MEDIAN(cleaned_price) AS median_price,
	ROUND(AVG(cleaned_price), 2) AS average_price,
	ROUND(AVG(cleaned_price) - MEDIAN(cleaned_price), 2) AS avg_median_difference,
	QUANTILE_CONT(cleaned_price, 0.25) AS q1_price,
	QUANTILE_CONT(cleaned_price, 0.75) AS q3_price
FROM cleaned_listings
WHERE cleaned_price IS NOT NULL
GROUP BY room_type
ORDER BY priced_listings DESC;

         room_type  priced_listings  ...  q1_price  q3_price
0  Entire home/apt             3629  ...    115.80    323.30
1     Private room              554  ...     56.74    162.63
2      Shared room               47  ...     18.86     53.22
3       Hotel room               21  ...    293.00    512.00

[4 rows x 7 columns]

## How much of the Denver market is classified as a high-price outlier, and how does that vary by room type?

In [5]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- How much of the Denver market is classified as a high-price outlier, and how does that vary by room type?
	
SELECT 
	room_type,
	price_status,
	COUNT(*) AS listings,
	ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY room_type), 2) AS percent_of_room_type
FROM cleaned_listings
WHERE price_status != 'Missing price'
GROUP BY room_type, price_status
ORDER BY room_type, listings DESC;

         room_type        price_status  listings  percent_of_room_type
0  Entire home/apt       Typical range      3416                 94.13
1  Entire home/apt  High price outlier       213                  5.87
2       Hotel room       Typical range        21                100.00
3     Private room       Typical range       532                 96.03
4     Private room  High price outlier        22                  3.97
5      Shared room       Typical range        47                100.00

## What does the overall distribution of nightly listing prices look like in Denver, and how strongly is it affected by extreme values?

In [85]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

-- What does the overall distribution of nightly listing prices look like in Denver, and how strongly is it affected by extreme values?

SELECT 
	id, name, neighbourhood_cleansed, property_type, room_type, accommodates, bedrooms, bathrooms, minimum_nights, cleaned_price, estimated_occupancy_l365d, estimated_revenue_l365d
FROM cleaned_listings
WHERE cleaned_price > 2000
ORDER BY cleaned_price DESC;

                    id  ... estimated_revenue_l365d
0             21712656  ...                       0
1             35382615  ...                 3795253
2             36515976  ...                       0
3   687686195085166733  ...                       0
4             45803041  ...                       0
5  1195056124079372458  ...                   20965
6             28057388  ...                       0
7   655281960656437689  ...                  166157
8   583955778204351946  ...                  133308

[9 rows x 12 columns]

In [84]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- What does the overall distribution of nightly listing prices look like in Denver, and how strongly is it affected by extreme values?

price_distribution AS (
SELECT 
	COUNT(cleaned_price) AS non_null_priced_listings,
	MIN(cleaned_price) AS min_price,
	QUANTILE_CONT(cleaned_price, 0.25) AS q1_price,
	MEDIAN(cleaned_price) AS median_price,
	ROUND(AVG(cleaned_price), 2) AS avg_price,
	QUANTILE_CONT(cleaned_price, 0.75) AS q3_price,
	MAX(cleaned_price) AS max_price,
	SUM(CASE WHEN cleaned_price > 500 THEN 1 ELSE 0 END) AS price_over_500,
	SUM(CASE WHEN cleaned_price > 1000 THEN 1 ELSE 0 END) AS price_over_1000,
	SUM(CASE WHEN cleaned_price > 2000 THEN 1 ELSE 0 END) AS price_over_2000,
	SUM(CASE WHEN cleaned_price > 5000 THEN 1 ELSE 0 END) AS price_over_5000,
	SUM(CASE WHEN cleaned_price > 10000 THEN 1 ELSE 0 END) AS price_over_10000
FROM cleaned_listings
)

SELECT 
	non_null_priced_listings,
	price_over_500, 
	ROUND(price_over_500 * 100.0 / non_null_priced_listings, 2) AS over_500_pct_of_price_listings,
	price_over_1000,
	ROUND(price_over_1000 * 100.0 / non_null_priced_listings, 2) AS over_1000_pct_of_price_listings,
	price_over_2000,
	ROUND(price_over_2000 * 100.0 / non_null_priced_listings, 2) AS over_2000_pct_of_price_listings,
	price_over_5000,
	ROUND(price_over_5000 * 100.0 / non_null_priced_listings, 2) AS over_5000_pct_of_price_listings,
	price_over_10000,
	ROUND(price_over_10000 * 100.0 / non_null_priced_listings, 2) AS over_10000_pct_of_price_listings
FROM price_distribution;

   non_null_priced_listings  ...  over_10000_pct_of_price_listings
0                      4251  ...                              0.05

[1 rows x 11 columns]

## How does host scale vary across Denver neighborhoods, and are particular neighborhoods disproportionately represented by multi-listing/professional hosts?

In [79]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- How does host scale vary across Denver neighborhoods, and are particular neighborhoods disproportionately represented by multi-listing/professional hosts?

neighbourhood_host_scale AS (
	SELECT 
		neighbourhood_cleansed,
		host_scale,
		COUNT(DISTINCT host_id) AS distinct_hosts,
		COUNT(*) AS listings,
		SUM(COUNT(DISTINCT host_id)) OVER (PARTITION BY neighbourhood_cleansed) AS total_hosts_in_neighbourhood,
		SUM(COUNT(DISTINCT host_id)) OVER (PARTITION BY host_scale) AS total_host_scale_hosts,
		SUM(COUNT(*)) OVER (PARTITION BY neighbourhood_cleansed) AS listings_in_neighbourhood,
		SUM(COUNT(*)) OVER (PARTITION BY host_scale) AS host_scale_listings
	FROM cleaned_listings
	GROUP BY neighbourhood_cleansed, host_scale
),

neighbourhood_host_scale_percentages AS (
	SELECT 
		neighbourhood_cleansed AS "Neighbourhood",
		host_scale AS "Host Scale",
		distinct_hosts AS "Distinct Hosts",
		total_hosts_in_neighbourhood AS "Total Hosts in Neighbourhood",
		ROUND(distinct_hosts * 100.0 / total_hosts_in_neighbourhood, 2) AS "Percent of Neighbourhood Hosts",
		listings AS "Listings",
		ROUND(listings * 100.0 / listings_in_neighbourhood, 2) AS "Percent of Neighbourhood Listings"
	FROM neighbourhood_host_scale
),

neighbourhood_host_scale_rank AS (
	SELECT 
		"Neighbourhood",
		"Host Scale",
		"Distinct Hosts",
		"Total Hosts in Neighbourhood",
		"Percent of Neighbourhood Hosts",
		ROW_NUMBER() OVER (PARTITION BY "Neighbourhood" ORDER BY "Percent of Neighbourhood Hosts" DESC) AS "Neighbourhood Hosts Percentage Rank",
		"Listings",
		"Percent of Neighbourhood Listings",
		ROW_NUMBER() OVER (PARTITION BY "Neighbourhood" ORDER BY "Percent of Neighbourhood Listings" DESC) AS "Neighbourhood Listings Percentage Rank"
	FROM neighbourhood_host_scale_percentages
)

SELECT * 
FROM neighbourhood_host_scale_rank
WHERE "Neighbourhood Listings Percentage Rank" = 1
ORDER BY neighbourhood;

    Neighbourhood  ... Neighbourhood Listings Percentage Rank
0     Athmar Park  ...                                      1
1         Auraria  ...                                      1
2           Baker  ...                                      1
3          Barnum  ...                                      1
4     Barnum West  ...                                      1
..            ...  ...                                    ...
72    West Colfax  ...                                      1
73  West Highland  ...                                      1
74       Westwood  ...                                      1
75       Whittier  ...                                      1
76        Windsor  ...                                      1

[77 rows x 9 columns]

In [74]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- How does host scale vary across Denver neighborhoods, and are particular neighborhoods disproportionately represented by multi-listing/professional hosts?

neighbourhood_host_scale AS (
	SELECT 
		neighbourhood_cleansed,
		host_scale,
		COUNT(DISTINCT host_id) AS distinct_hosts,
		COUNT(*) AS listings,
		SUM(COUNT(DISTINCT host_id)) OVER (PARTITION BY neighbourhood_cleansed) AS total_hosts_in_neighbourhood,
		SUM(COUNT(DISTINCT host_id)) OVER (PARTITION BY host_scale) AS total_host_scale_hosts,
		SUM(COUNT(*)) OVER (PARTITION BY neighbourhood_cleansed) AS listings_in_neighbourhood,
		SUM(COUNT(*)) OVER (PARTITION BY host_scale) AS host_scale_listings
	FROM cleaned_listings
	GROUP BY neighbourhood_cleansed, host_scale
)

SELECT 
	neighbourhood_cleansed AS "Neighbourhood",
	host_scale AS "Host Scale",
	distinct_hosts AS "Distinct Hosts",
	ROUND(distinct_hosts * 100.0 / total_hosts_in_neighbourhood, 2) AS "Percent of Neighbourhood Hosts",
	listings AS "Listings",
	ROUND(listings * 100.0 / listings_in_neighbourhood, 2) AS "Percent of Neighbourhood Listings"
FROM neighbourhood_host_scale
WHERE host_scale = 'Large/professional operator'
	AND total_hosts_in_neighbourhood >= 5
	AND listings_in_neighbourhood >= 10
ORDER BY "Percent of Neighbourhood Listings" DESC, "Percent of Neighbourhood Hosts" DESC;

      Neighbourhood  ... Percent of Neighbourhood Listings
0      Civic Center  ...                             64.29
1         City Park  ...                             54.24
2              Hale  ...                             43.96
3               CBD  ...                             43.03
4          Overland  ...                             34.09
..              ...  ...                               ...
56  South Park Hill  ...                              2.13
57          Skyland  ...                              2.13
58          Clayton  ...                              2.13
59  North Park Hill  ...                              1.64
60       Platt Park  ...                              1.61

[61 rows x 6 columns]

## Which neighborhoods have unusually high concentrations of each room type?

In [51]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Which neighborhoods have unusually high concentrations of each room type?

neighbourhood_listings AS (
	SELECT 
		n.neighbourhood,
		l.room_type,
		COUNT(l.id) AS listings,
		SUM(COUNT(l.id)) OVER (PARTITION BY n.neighbourhood) AS neighbourhood_total,
		SUM(COUNT(l.id)) OVER (PARTITION BY l.room_type) AS room_type_total,
		SUM(COUNT(l.id)) OVER () AS denver_total
	FROM 'neighbourhoods.csv' AS n
	LEFT JOIN cleaned_listings AS l
		ON n.neighbourhood = l.neighbourhood_cleansed
	GROUP BY n.neighbourhood, l.room_type
),

neighbourhood_listings_percentages AS (
	SELECT 
		neighbourhood AS "Neighbourhood",
		room_type AS "Room Type",
		listings AS "Neighbourhood Listings",
		neighbourhood_total AS "Neighbourhood Total",
		ROUND(listings * 100.0 / NULLIF(neighbourhood_total, 0), 2) AS "Neighbourhood Room Type Percentage",
		room_type_total AS "Room Type Total",
		ROUND(listings/room_type_total * 100, 2) AS "Percent of Denver Room Type Listings",
		ROUND(room_type_total * 100.0 / denver_total, 2) AS "Denver Room Type Share",
		ROUND(
			(listings * 1.0 / NULLIF(neighbourhood_total, 0))
			/
			(room_type_total * 1.0 / denver_total),
		2
		) AS "Location Quotient (LQ)"
	FROM neighbourhood_listings
	WHERE room_type IS NOT NULL
		AND listings >= 5
)

SELECT *,
	ROW_NUMBER() OVER (
		PARTITION BY "Room Type" 
		ORDER BY "Location Quotient (LQ)" DESC, "Neighbourhood Listings" DESC
	) AS "LQ Rank by Room Type"
FROM neighbourhood_listings_percentages 
WHERE "Location Quotient (LQ)" > 1
ORDER BY "LQ Rank by Room Type", "Location Quotient (LQ)" DESC;

                   Neighbourhood  ... LQ Rank by Room Type
0                       Overland  ...                    1
1                       Berkeley  ...                    1
2   Gateway - Green Valley Ranch  ...                    1
3                       Westwood  ...                    1
4                  West Highland  ...                    2
..                           ...  ...                  ...
62                           CBD  ...                   34
63                 Congress Park  ...                   35
64                   Athmar Park  ...                   36
65              University Hills  ...                   37
66                Jefferson Park  ...                   38

[67 rows x 10 columns]

## Within each neighborhood, what percentage of listings are Entire home/apt, Private room, Shared room, and Hotel room?

In [17]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Within each neighborhood, what percentage of listings are Entire home/apt, Private room, Shared room, and Hotel room?

neighbourhood_listings AS (
	SELECT 
		n.neighbourhood,
		l.room_type,
		COUNT(l.id) AS listings,
		SUM(COUNT(l.id)) OVER (PARTITION BY n.neighbourhood) AS neighbourhood_total
	FROM 'neighbourhoods.csv' AS n
	LEFT JOIN cleaned_listings AS l
		ON n.neighbourhood = l.neighbourhood_cleansed
	GROUP BY n.neighbourhood, l.room_type
)
	
SELECT 
	neighbourhood AS "Neighbourhood",
	room_type AS "Room Type",
	listings AS "Listings",
	neighbourhood_total AS "Neighbourhood Total",
	ROUND(listings * 100.0 / NULLIF(neighbourhood_total, 0), 2) AS "Percent of Neighbourhood Total",
	ROUND(
		SUM(listings) OVER (
		PARTITION BY neighbourhood
		ORDER BY listings DESC) * 100.0 
		/ NULLIF(neighbourhood_total, 0),
	2) AS "Cumulative Percentage"
FROM neighbourhood_listings 
ORDER BY neighbourhood, listings DESC;

    Neighbourhood  ... Cumulative Percentage
0     Athmar Park  ...                 87.88
1     Athmar Park  ...                100.00
2         Auraria  ...                100.00
3           Baker  ...                 88.79
4           Baker  ...                100.00
..            ...  ...                   ...
150      Whittier  ...                 83.33
151      Whittier  ...                 95.37
152      Whittier  ...                100.00
153       Windsor  ...                 80.00
154       Windsor  ...                100.00

[155 rows x 6 columns]

## Which Denver neighborhoods contain the most Airbnb listings, and what percentage of Denver's total Airbnb inventory does each neighborhood represent?

In [7]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- Which Denver neighborhoods contain the most Airbnb listings, and what percentage of Denver's total Airbnb inventory does each neighborhood represent?

neighbourhood_listings AS (
	SELECT 
		n.neighbourhood,
		COUNT(l.id) AS listings
	FROM 'neighbourhoods.csv' AS n
	LEFT JOIN cleaned_listings AS l
		ON n.neighbourhood = l.neighbourhood_cleansed
	GROUP BY n.neighbourhood
),

total AS (
	SELECT 
		COUNT(*) AS total_listings
	FROM cleaned_listings
)

SELECT 
	nl.neighbourhood AS "Neighbourhood",
	nl.listings AS "Listings",
	ROUND(nl.listings * 100.0 / t.total_listings, 2) AS "Percent of All Listings",
	ROUND(
		SUM(nl.listings) OVER (ORDER BY nl.listings DESC) * 100.0 
		/ t.total_listings, 
	2) AS "Cumulative Percentage"
FROM neighbourhood_listings AS nl
CROSS JOIN total AS t
ORDER BY nl.listings DESC;

                   Neighbourhood  ...  Cumulative Percentage
0                    Five Points  ...                   8.14
1                       Highland  ...                  14.17
2                  Union Station  ...                  18.75
3   Gateway - Green Valley Ranch  ...                  22.72
4                    West Colfax  ...                  26.67
..                           ...  ...                    ...
73                     Wellshire  ...                  99.90
74                       Auraria  ...                  99.90
75                Southmoor Park  ...                  99.98
76                       Kennedy  ...                 100.00
77                    Sun Valley  ...                 100.00

[78 rows x 4 columns]

## How many listings and what percentage of Denver's listings belong to each room_type?

In [6]:
WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
),

-- How many listings and what percentage of Denver's listings belong to each room_type? 
	
room_type_listings AS (
	SELECT 
		room_type,
		COUNT(*) AS listings
	FROM cleaned_listings
	GROUP BY room_type
),
	
total AS (
	SELECT 
		COUNT(*) AS total_listings
	FROM cleaned_listings
)

SELECT 
	r.room_type AS "Room Type",
	r.listings AS "Listings",
	ROUND(r.listings * 100.0 / t.total_listings, 2) AS "Percent of All Listings",
	ROUND(SUM(r.listings) OVER (ORDER BY r.listings DESC) * 100.0 / SUM(r.listings) OVER (), 2) AS "Cumulative Percentage"
FROM room_type_listings AS r
CROSS JOIN total AS t
ORDER BY "Listings" DESC;

         Room Type  Listings  Percent of All Listings  Cumulative Percentage
0  Entire home/apt      4233                    85.71                  85.71
1     Private room       631                    12.78                  98.48
2      Shared room        52                     1.05                  99.53
3       Hotel room        23                     0.47                 100.00

# Official Denver Airbnb Data Analysis-Ready CTEs

In [1]:
/* Official Denver Airbnb Data Analysis-Ready CTEs

- cleaned_listings v1 (frozen on Oct 1, 2026)
- cleaned_calendar v1 (frozen on Oct 1, 2026)
- cleaned_reviews v1 (frozen on Oct 1, 2026)

neighbourhoods.csv (keeping as a reference table)
- no cleaning CTE needed
- 1 neighbourhood is present in this dataset while not being present in the cleaned_listings snapshot - Sun Valley
- cleaned_listings.neighbourhood_cleansed serves as the primary geographic reference 
- neighbourhoods.csv is retained only as a reference for analyses requiring all defined neighborhoods, including those with zero listings.

*/

-- cleaned_listings

WITH base_listings AS (
	SELECT 
		id, last_scraped, source, name,
	
		host_id, host_name, host_location, 
		CASE 
			WHEN host_location IS NULL THEN 'No Location'
			WHEN LOWER(host_location) LIKE '%denver%' THEN 'Denver'
			WHEN TRIM(LOWER(host_location)) LIKE '%, co' OR LOWER(host_location) LIKE '%colorado%' THEN 'Other Colorado'
			WHEN TRIM(LOWER(host_location)) LIKE '%, __' OR LOWER(host_location) LIKE '%united states%' THEN 'Other US State'
			ELSE 'Other Country'
		END AS host_location_category, -- broader category for host_location 
	
		host_is_superhost, host_listings_count, calculated_host_listings_count, host_identity_verified, hosts_time_as_host_years,
		CASE
			WHEN calculated_host_listings_count = 1 THEN 'Single-listing host'
			WHEN calculated_host_listings_count BETWEEN 2 AND 4 THEN 'Small multi-listing host'
			WHEN calculated_host_listings_count BETWEEN 5 AND 9 THEN 'Medium operator'
			WHEN calculated_host_listings_count >= 10 THEN 'Large/professional operator'
		END AS host_scale, -- category column for calculated_host_listings_count ranges
	
		neighbourhood_cleansed, latitude, longitude,
	
		property_type, 
		CASE 
			WHEN property_type = 'Tiny home' THEN 'Specialty/Other'
			WHEN LOWER(property_type) LIKE '%home%' OR LOWER(property_type) LIKE '%bungalow%' OR LOWER(property_type) LIKE '%cottage%' THEN 'House/Home'
			WHEN LOWER(property_type) LIKE '%apartment%' OR LOWER(property_type) LIKE '%rental unit%' OR LOWER(property_type) LIKE '%loft%' THEN 'Apartment/Rental Unit'
			WHEN LOWER(property_type) LIKE '%condo%' THEN 'Condo'
			WHEN LOWER(property_type) LIKE '%townhouse%' THEN 'Townhouse'
			WHEN LOWER(property_type) LIKE '%guest%' THEN 'Guesthouse'
			WHEN LOWER(property_type) LIKE '%hotel%' OR LOWER(property_type) LIKE '%hostel%' OR LOWER(property_type) LIKE '%bed and breakfast%' THEN 'Hotel/Hospitality'
			WHEN LOWER(property_type) LIKE '%villa%' THEN 'Villa'
			ELSE 'Speciality/Other'
		END AS property_category, -- broader category for property_type
	
		room_type, accommodates, bedrooms, beds, amenities,
		 LEN(
			FROM_JSON(amenities, '["VARCHAR"]')
    	) AS amenity_count, -- converting amenities column to a list of VARCHAR values and counting amenities in the list for each listing

		bathrooms, bathrooms_text, 
		CASE 
			WHEN LOWER(bathrooms_text) LIKE '%private%' THEN 'Private'
			WHEN LOWER(bathrooms_text) LIKE '%shared%' THEN 'Shared'
			WHEN bathrooms_text IS NOT NULL THEN 'Standard'
			ELSE NULL
		END AS bathroom_type, -- categorizing the type of bathroom from bathrooms_text
	
		price,
		TRY_CAST(
            REPLACE(
                REPLACE(price, '$', ''),
                ',', ''
            ) AS DECIMAL(10,2)
        ) AS cleaned_price, -- converting VARCHAR price values to a usable numeric data type for calculations 
	
		minimum_nights, maximum_nights, has_availability, availability_30, availability_60, availability_90, availability_365, availability_eoy, estimated_occupancy_l365d,  estimated_revenue_l365d,
		CASE 
			WHEN minimum_nights <= 6 THEN 'Short stay'
			WHEN minimum_nights <= 27 THEN 'Medium Stay'
			WHEN minimum_nights <= 45 THEN 'Monthly stay'
			WHEN minimum_nights >= 46 THEN 'Extended stay'
		ELSE NULL
		END AS stay_policy, -- category column for minimum_nights ranges 
	
		first_review, last_review, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly,
		CASE 
			WHEN number_of_reviews_l30d >= 1 THEN 'Recently Reviewed'
			WHEN number_of_reviews_ltm >= 1 THEN 'Reviewed in Last Year'
			WHEN number_of_reviews >= 1 THEN 'Historically Reviewed'
			WHEN number_of_reviews = 0 THEN 'Never Reviewed'
		END AS listing_activity_status, -- category column for number_of_reviews_... fields
	
		review_scores_rating, review_scores_accuracy, review_scores_communication, review_scores_location, review_scores_value, reviews_per_month
FROM 'detailed_listings.csv'
),
	
room_type_price_quartiles AS (
	SELECT 
		room_type,
		QUANTILE_CONT(cleaned_price, 0.25) AS q1,
		QUANTILE_CONT(cleaned_price, 0.75) AS q3,
		QUANTILE_CONT(cleaned_price, 0.75) - QUANTILE_CONT(cleaned_price, 0.25) AS iqr
	FROM base_listings
	WHERE cleaned_price IS NOT NULL
	GROUP BY room_type
), -- intermediate CTE to calculate respective q1, q3, and iqr for each room_type

room_type_price_stats AS (
	SELECT 
		room_type,
		q1,
		q3,
		iqr,
		q1 - (1.5 * iqr) AS lower_bound,
		q3 + (1.5 * iqr) AS upper_bound
	FROM room_type_price_quartiles
), -- intermediate CTE to consolidate quartile values and calculated lower and upper bounds for each room_type

cleaned_listings AS (
	SELECT 
		b.*,
		CASE 
			WHEN b.cleaned_price IS NULL THEN 'Missing price'
			WHEN b.cleaned_price < p.lower_bound THEN 'Low price outlier'
			WHEN b.cleaned_price > p.upper_bound THEN 'High price outlier'
			ELSE 'Typical range' 
		END AS price_status -- category column for price, based on respective calculations for each room_type
	FROM base_listings AS b
	LEFT JOIN room_type_price_stats AS p
		ON b.room_type = p.room_type
), -- final cleaned_listings CTE

-- cleaned_calendar
	
cleaned_calendar AS (
	SELECT 
		c.listing_id,	
		CAST(c.date AS DATE) AS date,
		c.available,
		c.minimum_nights,
		c.maximum_nights,
		YEAR(c.date) AS year,
		MONTH(c.date) AS month,
		CAST(DATE_TRUNC('month', c.date) AS DATE) AS year_month
	FROM 'detailed_calendar.csv' AS c
	INNER JOIN cleaned_listings AS l
		ON c.listing_id = l.id
),

-- cleaned_reviews 

cleaned_reviews AS (
	SELECT 
		r.listing_id,
		r.id AS review_id,
		CAST(r.date AS DATE) AS date,
		r.reviewer_id,
		r.reviewer_name,
		r.comments,
		YEAR(r.date) AS year,
		MONTH(r.date) AS month,
		CAST(DATE_TRUNC('month', r.date) AS DATE) AS year_month
	FROM 'detailed_reviews.csv' AS r
	INNER JOIN cleaned_listings AS l
		ON r.listing_id = l.id
)

SELECT *
FROM cleaned_listings;

                       id  ...   price_status
0     1609550371032300730  ...  Typical range
1     1610255566922845326  ...  Typical range
2     1611181276254799867  ...  Typical range
3     1611820732712003794  ...  Missing price
4     1612605935579140935  ...  Typical range
...                   ...  ...            ...
4934   859538081301579295  ...  Typical range
4935   859552383590324134  ...  Typical range
4936   860987064624799346  ...  Missing price
4937   861713316149651018  ...  Typical range
4938   861874214056479492  ...  Typical range

[4939 rows x 55 columns]

Data Dictionary: https://docs.google.com/spreadsheets/d/1iWCNJcSutYqpULSQHlNyGInUvHg2BoUGoNRIGa6Szc4/edit?usp=sharing

# Screenshots (Hidden to Save Space)

![image-11](image-11.png)

![image-12](image-12.png)

![image-13](image-13.png)

![image-14](image-14.png)

**Denver Airbnb Analysis - Project Notes (Analytical Data Preparation)**
- price: 4,939 listings → 4,251 populated prices → 688 missing prices → 0 failed conversions → strongly right-skewed price distribution → at least one extreme contextual outlier requiring special handling.
- host_listings_count is based on the host's Airbnb-reported listing count, whereas calculated_host_listings_count is calculated from listings found in the current scrape/geographic dataset.
- bathrooms is the clean numeric measure for calculations and modeling, while bathrooms_text preserves bathroom type. Later, we can derive something like bathroom_type (private, shared, standard) from the text and potentially drop the raw text field from the final modeled dataset.
- About 96% of listings have a unique overall amenities combination (4,743 / 4,939). So the complete amenities string is not a useful categorical dimension.
- host_location_category: The category describes the host's reported profile location. It does not establish host residency or where the property owner lives.
- Reviews relationship: detailed_reviews.listing_id links reviews to cleaned_listings.id. All 638 current listings without review records have number_of_reviews = 0, confirming that their absence from the reviews table is expected. The raw reviews dataset contains 95 reviews associated with 8 listing IDs outside the current 4,939-listing universe. These records are excluded from cleaned_reviews using an INNER JOIN to cleaned_listings.

# Screenshots (Hidden to Save Space)

![image-2](image-2.png)

![image-3](image-3.png)

![image-4](image-4.png)

![image-5](image-5.png)

![image-6](image-6.png)

![image-7](image-7.png)

![image-8](image-8.png)

![image-9](image-9.png)

**Denver Airbnb Analysis - Project Notes (Introduction and Data Profiling):**

- Calendar table grain: One record appears to represent one listing on one calendar date.
  
- Potential calendar key: (listing_id, date).
  
- Review table grain: One record appears to represent one individual review.
  
- Potential review key: id.
  
- Potential relationship: reviews.listing_id → listings.id.
  
- Important limitation: Calendar availability cannot automatically be interpreted as confirmed occupancy.

- id is Airbnb's unique identifier for a listing, while host_id identifies the host.

- neighbourhood_cleansed is calculated by geocoding each listing's latitude/longitude against public/open neighborhood boundaries, making it the better standardized geography field for our neighborhood analysis.

- price is the daily price in local currency, and the $ symbol is an export artifact. That will matter when we clean/cast the field for SQL analysis.

- availability_365 measures days marked available over the next 365 days, but Inside Airbnb explicitly warns that unavailable dates can mean either guest-booked or host-blocked. That confirms why we shouldn't call 365 - availability_365 "occupied nights."

- calculated_host_listings_count is specifically the number of that host's listings found in the current scrape within the city/region, which makes it more useful for our Denver market-concentration analysis than host_total_listings_count, whose calculation Airbnb does not disclose.

- reviews_per_month is an Inside Airbnb calculated field representing average monthly reviews over the listing's lifetime, and the dictionary even documents its approximate calculation.

--------

- There are 10 more distinct listing IDs represented in the calendar than there are listings in detailed_listings.csv.

- Every listing id has exactly 365 rows each in detailed_calendar

- Finding: 10 listing IDs represented in the detailed calendar are absent from the detailed listings snapshot.

- Referential integrity: The detailed reviews table contains 95 historical reviews associated with 8 listing IDs that are not present in the current listings snapshot. Additionally, 638 current listings have no records in the detailed reviews table.

- Issue: price is stored as text and contains currency symbols.
Treatment: Remove the currency formatting and convert the field to a numeric datatype before performing price calculations.

- Price is strongly right-skewed. A global IQR cutoff over-flags listings because room types have different price structures. Room-type-specific IQR is a better screening method, but flagged values should not be removed automatically because many may be legitimate high-end listings.

- Roughly 300 of the 4,251 priced listings are being flagged as statistical upper outliers. That’s about 7% of priced listings, which is plausible for a heavily right-skewed market.

- The biggest finding is the difference between the average ($276.04) and median ($176.45). The mean is much higher, which is strong evidence that the price distribution is right-skewed: a relatively small number of very expensive listings are pulling the average upward.

- From an analysis perspective, however, it's extremely important. Denver's Airbnb supply in this dataset is overwhelmingly entire homes/apartments: 85.71%. That tells us room_type should probably become one of our major segmentation dimensions throughout the project.

detailed_listings
- Grain: One row per listing
- Primary key candidate: id
- Uniqueness: Confirmed in current dataset
- NULLs in key: None

room_type and property_type
- 100% complete with four standardized categories. Entire home/apartment listings dominate the Denver dataset (85.71%), followed by private rooms (12.78%). No cleaning required. Retain as a key categorical segmentation variable.
- room_type answers "How much of the property does the guest get?", while property_type gives a more specific description of "What kind of accommodation/property is it?"
- "property_type contained 38 categories with substantial class imbalance. Inspection indicated that rare categories represented legitimate accommodation types rather than obvious data-quality errors. The original field was therefore retained, with broader analytical groupings considered for segment-level analysis."
- Entire home/apt - Entire home has the most listings at 1589 listings and 32.17% share. 
- I'm noticing there are private room types that could be better classified in 'Hotel room', including room in hotel, ...aparthotel, ...boutique hotel, ...hostel.
----------
- room_type: Low-cardinality broad classification with four complete, standardized categories. Useful for high-level market segmentation.
- property_type: Higher-cardinality field with 38 legitimate accommodation categories and a long-tailed distribution. Provides additional structural detail within each room type. Retain the raw field; broader derived categories may be created later if needed for analysis.
- room_type and property_type are complementary rather than redundant. room_type provides a broad classification of the rental arrangement, while property_type provides more granular information about the physical accommodation. Therefore, both fields should be retained.

Data-Cleaning for price 
- Issue: price is stored as text and contains currency symbols.
- Treatment: Remove the currency formatting and convert the field to a numeric datatype before performing price calculations. New column: cleaned_price

Listing counts for price thresholds
- $500–$999.99: 336 listings
- $1,000–$1,999.99: 53 listings
- $2,000+: 9 listings

Errors, Extreme Values, and Outliers 
- Data error — a value is demonstrably incorrect or unusable.
- Extreme value — a legitimate but unusually large/small observation.
- Statistical outlier — a value falling outside a defined statistical criterion such as 1.5×IQR.

------------

neighbourhood_cleansed
- no missing values
- 77 legitimate categories
- no apparent capitalization/whitespace duplication
- meaningful variation in listing counts
- strong analytical relevance
- compatible with our later geographic analysis
- neighbourhoods.csv contains 78 Denver neighborhoods. All 77 neighborhoods represented in the current listings snapshot match the reference table. Sun Valley is present in the neighborhood reference data but has no listings in the current detailed_listings.csv snapshot.

------------

accommodates
- accommodates contains no null or zero values and ranges from 1–16 guests. Listings at the upper bound appear consistent with large-group properties based on bedroom, bathroom, and listing-description information.
- There's another important consideration: 16 appears repeatedly. You may eventually discover that 16 is effectively a platform/category ceiling rather than the exact physical maximum occupancy of every property. For this project, however, you don't need to resolve that yet. Just don't interpret 16 as necessarily meaning "this property can accommodate exactly 16 and no more."

----------

bathrooms and bathrooms_text
- bathrooms_text reliably represents bathroom count and provides bathroom information for many listings where the numeric bathrooms field is missing. Among records where both fields are populated, the numeric values are consistent except for one identified discrepancy.
- When both fields are populated, bathrooms and the numeric bathroom count represented by bathrooms_text are highly consistent. One conflicting record was identified (bathrooms = 2, bathrooms_text = '3.5 baths'). This supports using bathrooms_text as a fallback source for missing numeric bathroom counts, subject to explicit handling of special text values.
- bathrooms_text is the more complete bathroom field. It contains usable bathroom information for 885 of the 887 records where numeric bathrooms is missing. Conversely, only 4 records have a numeric bathrooms value while bathrooms_text is missing. When both fields are populated, the values are highly consistent aside from one identified discrepancy.

----------

bedrooms/beds
- bedrooms and beds exhibit partially overlapping missingness. Approximately 75.6% of listings have both fields populated, while only 1.4% are missing both. Because each field is available for hundreds of records where the other is missing, both should be retained rather than treated as substitutes.
- One listing contains an unusually inconsistent capacity profile: 15 bedrooms, 50 beds, but an accommodates value of only 2. Because several capacity fields conflict, the record is flagged as a potential data-quality anomaly rather than automatically corrected or removed.
- For the eventual analysis, I would treat accommodates as your primary capacity variable, with bedrooms and beds as supplementary property characteristics. It's complete and directly represents the listing's stated guest capacity.

---------

minimum_nights
- Minimum-stay requirements are highly concentrated at a small number of values. One-night stays are the most common requirement (27.1%), while 29- and 30-night minimums collectively account for approximately 46.9% of listings. This suggests a substantial segment of the Denver Airbnb market is oriented toward longer stays. Extreme minimum-stay values also exist, reaching 500 nights, but these represent atypical listings and should not be interpreted as representative of the market.
- Minimum-stay policies show a highly polarized distribution. Approximately 46.9% of listings require 29–30 nights, while approximately 49.8% allow stays of six nights or fewer. Listings with minimum stays between 7 and 28 nights are comparatively rare at less than 1%.

----------

availability
- Inside Airbnb's available calendar status doesn't tell us why a date is unavailable. A host may have blocked dates, stopped accepting reservations temporarily, restricted the calendar, or the date may actually be booked.
- Calendar availability is substantially lower in the near term. Listings average approximately 30% availability over the next 30 days, compared with roughly 50–62% across subsequent future periods. This pattern may reflect a combination of reservations, host calendar restrictions, and other availability settings and should not be interpreted directly as occupancy.
- Availability fields were complete and remained within their expected bounds (0–30, 0–60, 0–90, and 0–365). Availability was substantially lower in the immediate 30-day window than in later future periods. Zero availability was particularly common over the next 30 days (35.1%), declining as the observation window expanded. Because unavailable calendar dates may represent bookings or host-imposed restrictions, availability is treated as a calendar-availability measure rather than an occupancy measure.
- The cumulative availability fields are logically consistent across the dataset. No listing has a shorter-window availability value greater than a longer-window availability value.

--------

- 638 listings have zero lifetime reviews, and exactly 638 listings have NULL reviews_per_month.
- reviews_per_month is NULL precisely for listings with no reviews rather than representing missing data in the conventional sense.
- For lifetime reviews, the middle 50% is roughly 3–85 reviews, yet the maximum reaches 1,798. Your earlier mean of 71.81 versus median of 21 reinforces the strong right skew.
- The LTM variable shows the same general phenomenon, although less extreme: 25% of listings received no reviews at all in the previous 12 months, while the upper 10% had at least roughly 38.
- This also tells us that when we eventually compare neighborhoods, median review activity may often be more representative than average review activity.
- Most Denver listings show some recent review activity, with approximately 72% recording at least one review during the previous 12 months. However, only about 43% recorded a review during the previous 30 days. Approximately 15% have historical reviews but none within the past year, while roughly 13% have never been reviewed.

number_of_reviews
- The mean being more than 3× the median, plus the 1,798 maximum, strongly suggests a right-skewed distribution. A relatively small number of highly reviewed listings are pulling the average upward.
- 638 listings have 0 lifetime reviews → about 12.9%

number_of_reviews_ltm
- That zero count is analytically interesting. A listing can have historical reviews but no recent reviews, which could indicate lower recent review activity, a listing that isn't currently operating much, or other factors. We shouldn't automatically call that "low demand."
- 1,365 listings have 0 reviews in the last 12 months → about 27.6%

number_of_reviews_l30d
- 2,803 listings have 0 reviews in the last 30 days → about 56.8%
- Finding: Recent review activity is highly concentrated. 56.8% of Denver listings recorded no reviews during the previous 30 days, resulting in a median of 0 despite a mean of 1.23 reviews per listing.

reviews_per_month
- is NULL precisely for listings with no reviews rather than representing missing data in the conventional sense.
- reviews_per_month contains 638 NULL values, all corresponding exactly to listings with zero lifetime reviews. These NULLs represent listings for which a monthly review rate has not been established rather than apparent data-quality errors.

---------

ratings
- Across all seven rating fields, you have 4,301 non-null values and 638 NULL values. That is especially notable because you previously found exactly 638 listings with number_of_reviews = 0.
- Your final query also found zero listings where number_of_reviews >= 1 while all seven review-score fields were NULL. So the evidence strongly suggests that the rating NULLs are structural: listings with no reviews do not have ratings.
- Ratings are extremely concentrated near 5.0. Every rating category has a median above 4.85, and most have Q3 = 5. This means these variables have a strong ceiling effect. A 4.7 rating might sound excellent in isolation, but within this particular market it could actually be relatively weak.
- Second, communication and check-in appear strongest. Their averages are 4.91 and 4.92 and medians are 4.98 and 4.97. Hosts generally seem to receive exceptionally high scores on these dimensions.
- Third, value stands out as the weakest dimension. Its mean of 4.79, median of 4.86 and Q1 of 4.74 are all noticeably below the other categories. That's potentially meaningful for our eventual pricing analysis: we may want to investigate whether higher-priced listings receive lower review_scores_value.
- Fourth, location is also somewhat lower than operational categories such as communication and check-in. That's interesting because location is largely a property characteristic rather than something a host can improve operationally.
- Listings with zero reviews have NULL review scores, while listings with at least one review have values for all seven review-score fields.
- Review-score fields contain 638 NULL values, corresponding exactly to listings with zero reviews. These NULLs represent unrated listings rather than erroneous missing data and will therefore be retained.

----------

host 
- Single-listing hosts make up 83.91% of all hosts, but account for only 56.37% of Denver's Airbnb listings.
- Hosts with more than 10 listings represent only 0.96% of hosts, yet control 15.02% of the listings in this dataset.
- 83.91% of hosts have exactly one listing, accounting for 56.37% of listings.
- 16.09% of hosts have multiple listings, accounting for 43.63% of listings.
- Hosts with more than 10 listings are only 0.96% of hosts, but account for 15.02% of listings.
- The 10 largest individual hosts account for 7.41% of all listings.
- Pricing: Superhost listings have a median asking price of $206 versus $135.82, roughly 52% higher. The average is also substantially higher ($323.77 vs. $212.46). Because both groups have averages substantially above their medians, that's another indication that price is right-skewed and reinforces our decision to pay attention to medians.
- Review activity: Superhost listings average 2.09 reviews/month versus 1.15 for non-Superhosts. That's a more useful comparison than the raw total-review numbers because there are different numbers of listings in each group.
- Large-host presence varies substantially across Denver neighborhoods. Some neighborhoods have relatively high shares of listings operated by hosts with portfolios exceeding 10 Denver listings.
- Validated calculated_host_listings_count against an independently calculated COUNT(*) by host_id. No discrepancies were identified among the 4,939 Denver listings, indicating that the field accurately represents the number of listings associated with each host within this dataset.

--------

estimated occupancy and revenue 
- Estimated Occupancy: Complete across all 4,939 listings, ranging from 0–255 estimated occupied nights. The median is 70 nights versus a mean of 103.91, indicating a right-skewed distribution. 1,365 listings (27.6%) have zero estimated occupancy. No negative or >365 values were identified.
- Estimated Revenue: Available for 4,251 listings and missing for 688. Median estimated annual revenue is $15,979 compared with a mean of $28,047.32, indicating substantial right skew from high-revenue listings. The maximum is $3,795,253.
- Revenue Nulls: All 688 missing estimated-revenue values correspond exactly to listings with missing prices. No listing with a populated price has missing estimated revenue.
- Metric Dependency: For all comparable records, estimated_revenue_l365d equals price × estimated_occupancy_l365d. Estimated revenue should therefore be treated as a derived estimate, not an independently observed measure of actual Airbnb revenue.

## detailed_calendar.csv

- Grain: one listing-calendar-date per row
- Composite key: (listing_id, date)
- detailed_calendar.csv grain and key: The dataset contains 1,806,385 rows representing 4,949 distinct listings. Each listing has exactly 365 records corresponding to 365 distinct dates. No duplicate (listing_id, date) combinations or NULL values in either key field were identified. Therefore, one row represents one listing on one calendar date, and (listing_id, date) is validated as the composite primary key.
- Cross-dataset integrity: detailed_calendar.csv contains 4,949 listing IDs compared with 4,939 listings in detailed_listings.csv, indicating 10 calendar listing IDs are absent from the current listings snapshot.
- 4,305 listings (87.0%) cover June 30, 2026 → June 29, 2027.
- 644 listings (13.0%) cover July 2, 2026 → July 1, 2027.
- Calendar date coverage: Each of the 4,949 listings contains exactly 365 unique calendar dates, but listings do not all share the same calendar window. 4,305 listings (87.0%) span June 30, 2026 through June 29, 2027, while 644 listings (13.0%) span July 2, 2026 through July 1, 2027. This suggests the calendar records were captured across different scrape dates/batches. Date-level analyses should account for differences in listing coverage near the boundaries of the dataset.

----------

availability
- Availability: The available field is complete and contains only the expected Boolean values. Across all 1,806,385 listing-date records, 1,021,669 (56.56%) are marked available and 784,716 (43.44%) are marked unavailable.
- False means the date is not available on the Airbnb calendar, but we don't know whether that's because it was booked, host-blocked, restricted, or unavailable for some other reason.
- Listing-level calendar availability: Availability varies substantially across Denver listings. The median listing is marked available for 236 of its 365 calendar dates (64.7%), compared with a mean of 206.44 days (56.6%). Approximately 40.9% of listings are available for at least 271 days, while 7.7% have zero available dates. These differences demonstrate substantial variation in calendar availability across listings. Because unavailable dates may represent either reservations or host-imposed restrictions, these values should not be interpreted directly as occupancy.
- Cross-dataset availability validation: Calendar-derived annual availability was compared with detailed_listings.availability_365 for all 4,939 listings represented in both datasets. 4,938 listings (99.98%) matched exactly. One listing was inconsistent: availability_365 reported 0 available days, while its 365 calendar records contained 207 available and 158 unavailable dates. The calendar record itself contained a complete 365-day window and plausible variation in availability over time. Because the source of the discrepancy cannot be determined from the available data, the record is retained and documented as a cross-dataset inconsistency rather than corrected.
- Calendar availability is substantially lower in the immediate future, rises considerably farther into the booking window, peaks around November–December in this snapshot, and then declines somewhat in later spring/summer months.

------------

minimum and maximum nights
- Minimum-stay requirements are considerably more dynamic than maximum-stay requirements. Approximately 24.5% of listings have multiple minimum-night requirements across their 365-day calendar, compared with only about 2.5% having multiple maximum-night requirements.
- That makes intuitive analytical sense as something worth investigating: hosts may configure different minimum stays for different dates. We don't need to determine why yet.
- Calendar stay requirements: minimum_nights and maximum_nights are complete across all 1,806,385 calendar records. Calendar-level minimum stays range from 1–500 nights, while maximum stays range from 1–1,125 nights. Stay requirements are not necessarily constant within a listing's calendar. Of 4,949 listings, 1,213 (24.5%) have multiple minimum-night requirements across their 365 dates, while 125 (2.5%) have multiple maximum-night requirements. Minimum-stay restrictions therefore exhibit substantially greater date-level variation than maximum-stay restrictions.
- The listing-level stay-restriction values are highly consistent with calendar-level restrictions, but calendar data contains additional date-specific variation that the listing-level fields do not capture.
- - Cross-dataset stay-restriction validation: Listing-level minimum_nights and maximum_nights were compared against all calendar-level values for each listing. Among 4,939 listings represented in both datasets, 4,938 (99.98%) had a listing-level minimum-night value occurring on at least one calendar date, and 4,938 (99.98%) had a listing-level maximum-night value occurring on at least one calendar date. Calendar-level restrictions can vary by date, particularly minimum stays, so listing-level fields should not be interpreted as necessarily applying uniformly across the entire 365-day calendar.
- Cross-dataset anomaly: One listing was identified as the sole exception across multiple listing-to-calendar validation tests. Its listing-level record reports minimum_nights = 0, maximum_nights = 0, and availability_365 = 0, while its calendar contains a complete 365-day window with minimum_nights = 1, maximum_nights = 365, and 207 available dates. The remaining 4,938 listings shared by both datasets reconcile successfully across these checks. Because the cause of the discrepancy cannot be established from the source data, the listing should be flagged as an anomalous cross-dataset record rather than automatically corrected.
- Stay-restriction consistency: 3,608 of 1,806,385 calendar records (~0.20%) have minimum_nights > maximum_nights. These records are highly concentrated, affecting only 14 of 4,949 listings (~0.28%). The condition appears logically inconsistent under a straightforward interpretation of minimum- and maximum-stay restrictions, but the records are not automatically classified as source errors because the underlying Airbnb rule semantics may be more complex. The affected listings were flagged for further inspection rather than corrected or removed.
- Calendar stay-rule consistency: 3,608 calendar records (~0.20%) have minimum_nights > maximum_nights, affecting 14 of 4,949 calendar listings (~0.28%). The condition is highly concentrated: 11 listings account for nearly all affected records, with 270–365 affected dates each, while three listings are affected on only one date. Most heavily affected listings have a constant 29-night minimum while their maximum-night restriction varies by date. Because the underlying Airbnb booking-rule semantics cannot be fully determined from the source data, these records are retained and flagged rather than automatically classified as errors or corrected.

## detailed_reviews.csv

- detailed_reviews grain/key: One row represents one individual Airbnb review. id is a valid primary-key candidate in the current dataset: all 354,741 review IDs are non-NULL and unique.
- Reviews/listings relationship: detailed_reviews.listing_id relates reviews to detailed_listings.id. Of 354,741 review records, 95 historical reviews reference 8 listing IDs that are absent from the current listings snapshot. Conversely, 638 current listings have no records in the detailed reviews table. The unmatched historical reviews are retained because the reviews dataset spans many years and may include listings no longer represented in the current snapshot.
- Review-count reconciliation: For all 4,939 current listings, detailed_listings.number_of_reviews exactly equals the number of corresponding records in detailed_reviews.csv. This includes the 638 listings reporting zero lifetime reviews, confirming that their absence from detailed_reviews is consistent with the listing-level review count rather than apparent missing review data.
- Reviewer-field completeness: All 354,741 review records contain both a reviewer_id and reviewer_name. No records contain a reviewer ID without a name or a name without an ID. Reviewer-level analysis should use reviewer_id rather than reviewer_name as the identifier.
- For every listing included by the INNER JOIN, the listing table's first_review and last_review fields exactly agree with the minimum and maximum dates observed in detailed_reviews.csv.