In [1]:
print("Denver Airbnb Analysis")

Denver Airbnb Analysis

In [2]:
total_listings = 4939

print(total_listings)

4939

In [3]:
total_listings = 4939
priced_listings = 4251

missing_prices = total_listings - priced_listings

print(missing_prices)

688

In [4]:
median_price = 176.45
room_type = "Entire home/apt"

print(type(median_price))
print(type(room_type))

<class 'float'>
<class 'str'>

In [7]:
total_listings = 4939
priced_listings = 4251

missing_prices = total_listings - priced_listings

populated_prices_pct = (priced_listings / total_listings) * 100

print(missing_prices)
print(type(missing_prices))
print(round(populated_prices_pct, 2))
print(type(populated_prices_pct))
print(f"Listings with populated prices: {populated_prices_pct:.2f}%")

688
<class 'int'>
86.07
<class 'float'>
Listings with populated prices: 86.07%

In [8]:
neighborhoods = ["Hale", "Washington Park", "Five Points"]
print(neighborhoods[0])

Hale

In [9]:
listing = {
    "id": 12345,
    "room_type": "Entire home/apt",
    "bedrooms": 2,
    "price": 175.50
}

print(listing["price"])

175.5

In [ ]:
neighborhoods = ["CBD", "Five Points", "Highland", "Overland", "Platt Park"]

print(neighborhoods[0])
print(neighborhoods[-1])

len(neighborhoods)

CBD
Platt Park

5

In [15]:
airbnb_listing = {
    "listing_id": 235124,
    "neighborhood": "Five Points",
    "bedrooms": 2,
    "price": 215.25
}

print(airbnb_listing["neighborhood"])

price_per_bedroom = airbnb_listing["price"] / airbnb_listing["bedrooms"]
print(round(price_per_bedroom, 2))
print(f"Price per bedroom: ${price_per_bedroom:.2f}")

Five Points
107.62
Price per bedroom: $107.62

In [16]:
bedrooms = 2

if bedrooms == 1:
    print("One Bedroom")
elif bedrooms == 2:
    print("Two Bedrooms")
else:
    print("Other")

Two Bedrooms

In [25]:
airbnb_listing = {
    "listing_id": 235124,
    "neighborhood": "Five Points",
    "bedrooms": 2,
    "price": 215.25
}

if airbnb_listing["bedrooms"] == 1:
    bedroom_category = "One Bedroom"
elif 2 <= airbnb_listing["bedrooms"] <= 3:
    bedroom_category = "Small Multi-Bedroom"
elif airbnb_listing["bedrooms"] >= 4:
    bedroom_category = "Large Property"
else:
    bedroom_category = "Studio"

print(bedroom_category)

if airbnb_listing["price"] < 100:
    price_category = "Budget"
elif 100 <= airbnb_listing["price"] < 250:
    price_category = "Mid-Range"
else:
    price_category = "Premium"

print(price_category)

Small Multi-Bedroom
Mid-Range

In [26]:
neighborhoods = ["Hale", "Five Points", "Highland"]

for neighborhood in neighborhoods:
    print(neighborhood)

Hale
Five Points
Highland

In [27]:
prices = [85, 150, 275, 95, 320]

for price in prices:
    if price < 100:
        print("Budget")
    elif price < 250:
        print("Mid-Range")
    else:
        print("Premium")

Budget
Mid-Range
Premium
Budget
Premium

In [39]:
listings = [
    {"id": 101, "neighborhood": "Five Points", "price": 175, "bedrooms": 2},
    {"id": 102, "neighborhood": "Hale", "price": 90, "bedrooms": 1},
    {"id": 103, "neighborhood": "Highland", "price": 325, "bedrooms": 3}
]

for neighborhood_price in listings:
    neighborhood = neighborhood_price["neighborhood"]
    price = neighborhood_price["price"]

    
    print(f"{neighborhood}: ${price:.2f}")

Five Points: $175.00
Hale: $90.00
Highland: $325.00

In [43]:
listings = [
    {"id": 101, "neighborhood": "Five Points", "price": 175, "bedrooms": 2},
    {"id": 102, "neighborhood": "Hale", "price": 90, "bedrooms": 1},
    {"id": 103, "neighborhood": "Highland", "price": 325, "bedrooms": 3}
]

for neighborhood_price in listings:
    print(f"{neighborhood_price['neighborhood']}: ${neighborhood_price['price']:.2f}")

Five Points: $175.00
Hale: $90.00
Highland: $325.00

In [48]:
listings = [
    {"id": 101, "neighborhood": "Five Points", "price": 175, "bedrooms": 2},
    {"id": 102, "neighborhood": "Hale", "price": 90, "bedrooms": 1},
    {"id": 103, "neighborhood": "Highland", "price": 325, "bedrooms": 3}
]

for price_category in listings:
    
    neighborhood = price_category["neighborhood"]
    price = price_category["price"]

    if price < 100:
        category = "Budget"
    elif 100 <= price < 250:
        category = "Mid-Range"
    else:
        category = "Premium"

    print(f"{neighborhood}: {category}")

Five Points: Mid-Range
Hale: Budget
Highland: Premium

In [53]:
listings = [
    {"id": 101, "neighborhood": "Five Points", "price": 175, "bedrooms": 2},
    {"id": 102, "neighborhood": "Hale", "price": 90, "bedrooms": 1},
    {"id": 103, "neighborhood": "Highland", "price": 325, "bedrooms": 3}
]

total_price = 0

for listing in listings:
    total_price += listing["price"]

avg_price = total_price / len(listings)

print(f"${avg_price:.2f}")

$196.67

In [54]:
def classify_price(price):
    if price < 100:
        category = "Budget"
    elif price < 250:
        category = "Mid-Range"
    else: 
        category = "Premium"
    return category

print(classify_price(90))
print(classify_price(175))
print(classify_price(325))

Budget
Mid-Range
Premium

In [2]:
listings = [
    {"id": 101, "neighborhood": "Five Points", "price": 175, "bedrooms": 2},
    {"id": 102, "neighborhood": "Hale", "price": 90, "bedrooms": 1},
    {"id": 103, "neighborhood": "Highland", "price": 325, "bedrooms": 3}
]

def classify_price(price):
    if price < 100:
        category = "Budget"
    elif price < 250:
        category = "Mid-Range"
    else: 
        category = "Premium"
    return category

for listing in listings:
    price_category = classify_price(listing["price"])
    print(f"{listing["neighborhood"]}: {price_category}")

Five Points: Mid-Range
Hale: Budget
Highland: Premium

In [3]:
import pandas as pd

df = pd.DataFrame(listings)

df

    id neighborhood  price  bedrooms
0  101  Five Points    175         2
1  102         Hale     90         1
2  103     Highland    325         3

In [5]:
df["price"]

0    175
1     90
2    325
Name: price, dtype: int64

In [4]:
df[["neighborhood", "price"]]

  neighborhood  price
0  Five Points    175
1         Hale     90
2     Highland    325

In [6]:
df[df["price"] > 100]

    id neighborhood  price  bedrooms
0  101  Five Points    175         2
2  103     Highland    325         3

In [7]:
df.loc[df["price"] > 100, ["neighborhood", "price"]]

  neighborhood  price
0  Five Points    175
2     Highland    325

In [ ]:
# Display only neighborhood and bedrooms
df[["neighborhood", "bedrooms"]]

  neighborhood  bedrooms
0  Five Points         2
1         Hale         1
2     Highland         3

In [9]:
# Display listings priced at $150 or higher
df[df["price"] >= 150]

    id neighborhood  price  bedrooms
0  101  Five Points    175         2
2  103     Highland    325         3

In [10]:
# Display only neighborhood and price for listings with 2 or more bedrooms
df.loc[df["bedrooms"] >= 2, ["neighborhood", "price"]]

  neighborhood  price
0  Five Points    175
2     Highland    325

In [13]:
# Display listings with prices between $100 and $300, inclusive
df[(df["price"] >= 100) & (df["price"] <= 300)]

    id neighborhood  price  bedrooms
0  101  Five Points    175         2

In [14]:
df[df["price"].between(100, 300)]

    id neighborhood  price  bedrooms
0  101  Five Points    175         2

In [15]:
df["price"].mean()

np.float64(196.66666666666666)

In [16]:
df.groupby("neighborhood")["price"].mean()

neighborhood
Five Points    175.0
Hale            90.0
Highland       325.0
Name: price, dtype: float64

In [17]:
df.groupby("neighborhood")["price"].mean().reset_index()

  neighborhood  price
0  Five Points  175.0
1         Hale   90.0
2     Highland  325.0

In [ ]:
# Average listing price.
df["price"].mean()

np.float64(196.66666666666666)

In [19]:
# Median listing price.
df["price"].median()

np.float64(175.0)

In [20]:
# Maximum listing price.
df["price"].max()

np.int64(325)

In [21]:
# Total number of bedrooms across all listings.
df["bedrooms"].sum()

np.int64(6)

In [22]:
# Number of listings.
len(df)

3

In [25]:
# Average listing price for each bedroom count.
df.groupby("bedrooms")["price"].mean()

bedrooms
1     90.0
2    175.0
3    325.0
Name: price, dtype: float64

In [26]:
df["price"].agg(["mean", "median", "min", "max"])

mean      196.666667
median    175.000000
min        90.000000
max       325.000000
Name: price, dtype: float64

In [27]:
df.groupby("bedrooms").agg(
    listing_count=("id", "count"),
    avg_price=("price", "mean"),
    median_price=("price", "median")
)

          listing_count  avg_price  median_price
bedrooms
1                     1       90.0          90.0
2                     1      175.0         175.0
3                     1      325.0         325.0

In [33]:
# Create price_per_bedroom by dividing price by bedrooms
df["price_per_bedroom"] = df["price"] / df["bedrooms"]
df["price_per_bedroom"]

0     87.500000
1     90.000000
2    108.333333
Name: price_per_bedroom, dtype: float64

In [36]:
# Create is_premium containing True for listings priced at $250 or higher
df["is_premium"] = df["price"] >= 250
df["is_premium"]

0    False
1    False
2     True
Name: is_premium, dtype: bool

In [44]:
# Create price_difference_from_mean by subtracting the overall average listing price from each listing's price
df["price_difference_from_mean"] = df["price"] - df["price"].mean()
df["price_difference_from_mean"]

0    -21.666667
1   -106.666667
2    128.333333
Name: price_difference_from_mean, dtype: float64

In [45]:
# Display only neighborhood, price, price_per_bedroom, is_premium, and price_difference_from_mean
df["price_difference_from_mean"] = df["price"] - df["price"].mean()
df["is_premium"] = df["price"] >= 250
df["price_per_bedroom"] = df["price"] / df["bedrooms"]

df[["neighborhood", "price", "price_per_bedroom", "is_premium", "price_difference_from_mean"]]

,neighborhood,price,price_per_bedroom,is_premium,price_difference_from_mean
0,Five Points,175,87.500000,False,-21.666667
1,Hale,90,90.000000,False,-106.666667
2,Highland,325,108.333333,True,128.333333

In [46]:
# Use your existing classify_price() function to create a price_category column.

def classify_price(price):
    if price < 100:
        category = "Budget"
    elif price < 250:
        category = "Mid-Range"
    else: 
        category = "Premium"
    return category

df["price_category"] = df["price"].apply(classify_price)

df[["neighborhood", "price", "price_per_bedroom", "is_premium", "price_difference_from_mean", "price_category"]]

,neighborhood,price,price_per_bedroom,is_premium,price_difference_from_mean,price_category
0,Five Points,175,87.500000,False,-21.666667,Mid-Range
1,Hale,90,90.000000,False,-106.666667,Budget
2,Highland,325,108.333333,True,128.333333,Premium

In [47]:
df["price"].isna()

0    False
1    False
2    False
Name: price, dtype: bool

In [48]:
df["price"].isna().sum()

np.int64(0)

In [49]:
df.dtypes

id                              int64
neighborhood                      str
price                           int64
bedrooms                        int64
price_per_bedroom             float64
is_expensive                     bool
price_difference_from_mean    float64
is_premium                       bool
price_category                    str
dtype: object

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          3 non-null      int64
 1   neighborhood                3 non-null      str
 2   price                       3 non-null      int64
 3   bedrooms                    3 non-null      int64
 4   price_per_bedroom           3 non-null      float64
 5   is_expensive                3 non-null      bool
 6   price_difference_from_mean  3 non-null      float64
 7   is_premium                  3 non-null      bool
 8   price_category              3 non-null      str
dtypes: bool(2), float64(2), int64(3), str(2)
memory usage: 306.0 bytes

In [51]:
df.sort_values("price", ascending=False)

,id,neighborhood,price,bedrooms,price_per_bedroom,is_expensive,price_difference_from_mean,is_premium,price_category
2,103,Highland,325,3,108.333333,True,128.333333,True,Premium
0,101,Five Points,175,2,87.500000,False,-21.666667,False,Mid-Range
1,102,Hale,90,1,90.000000,False,-106.666667,False,Budget

In [ ]:
# Count the number of missing prices in df_practice
df_practice = df.copy()
df_practice.loc[df_practice["neighborhood"] == "Hale", "price"] = float("nan")

df_practice["price"].isna().sum()

np.int64(1)

In [55]:
# Display only the rows where price is missing
df_practice = df.copy()
df_practice.loc[df_practice["neighborhood"] == "Hale", "price"] = float("nan")

df_practice[df_practice["price"].isna()]

,id,neighborhood,price,bedrooms,price_per_bedroom,is_expensive,price_difference_from_mean,is_premium,price_category
1,102,Hale,NaN,1,90.0,False,-106.666667,False,Budget

In [56]:
# Calculate the average price, excluding missing values
df_practice = df.copy()
df_practice.loc[df_practice["neighborhood"] == "Hale", "price"] = float("nan")

df_practice["price"].mean()

np.float64(250.0)

In [57]:
# Sort listings by price from highest to lowest
df_practice = df.copy()
df_practice.loc[df_practice["neighborhood"] == "Hale", "price"] = float("nan")

df_practice.sort_values("price", ascending=False)

,id,neighborhood,price,bedrooms,price_per_bedroom,is_expensive,price_difference_from_mean,is_premium,price_category
2,103,Highland,325.0,3,108.333333,True,128.333333,True,Premium
0,101,Five Points,175.0,2,87.500000,False,-21.666667,False,Mid-Range
1,102,Hale,NaN,1,90.000000,False,-106.666667,False,Budget

In [ ]:
# Inspect the DataFrame's data types using .dtypes
df_practice = df.copy()
df_practice.loc[df_practice["neighborhood"] == "Hale", "price"] = float("nan")

df_practice.dtypesm

id                              int64
neighborhood                      str
price                         float64
bedrooms                        int64
price_per_bedroom             float64
is_expensive                     bool
price_difference_from_mean    float64
is_premium                       bool
price_category                    str
dtype: object

In [63]:
# Calculate the percentage of listings with missing prices, using pandas rather than a manually entered count.
df_practice = df.copy()
df_practice.loc[df_practice["neighborhood"] == "Hale", "price"] = float("nan")

df_practice["missing_prices"] = df_practice["price"].isna().sum()

df_practice["percentage_missing_prices"] = df_practice["missing_prices"] * 100 / len(df_practice)

df_practice["percentage_missing_prices"]

0    33.333333
1    33.333333
2    33.333333
Name: percentage_missing_prices, dtype: float64

In [64]:
missing_price_pct = df_practice["price"].isna().mean() * 100

print(f"Missing prices: {missing_price_pct:.2f}%")

Missing prices: 33.33%